### ISSUE TITLE
Document how to understand what collections are active for the Kabanero Instance.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/docs#100]
When trying to diagnose a user issue, it was not apparent to the user how to validate what Kabanero repository and collections were used, and active for this Kabanero instance.

There are two ways:  Via the Kanbanero landing page extension in the OKD console, and displaying the configured kabanero CR using the `oc` cli:

`oc get kabanero -n kabanero -o yaml`

The above example assumes the configured Kabanero instance is installed in the `kabanero` namespace.

**Comment by ManasiGandhi** [comment]
@stephenkinder Are there any links to topics that I can refer to, with some more details on validating what Kabanero repository and collections were used and active for a specific  Kabanero instance?

**Comment by ManasiGandhi** [comment]
The updates can be seen here https://github.com/kabanero-io/docs/blob/5be4db84c281d962e658f7d1cca5efb7a7810f00/ref/general/kabanero-cli.adoc#show-the-active-repository-and-collections-for-a-kabanero-instance
