### ISSUE TITLE
Write a collections guide that uses the Eclipse IDE

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#102]
Rather than have a guide for each collection, we decided to write guides that covered the developer experience of using different collections with either:

- Appsody CLI
- VS Code
- Eclipse

The microprofile and Spring guides explain how to use these collections with the Appsody CLI. 
#48 will cover using Nodejs-express with VS Code

This issue needs to cover using a collection with the Eclipse IDE.

Suggest we either go for one of the other Nodejs collections, or OpenLiberty when ready.

**Comment by mingcyu** [comment]
@SueChaplain Would you be agreeable to using this issue to cover Eclipse Che?

**Comment by SueChaplain** [comment]
@mingcyu  - I created this one because a while back we agreed to base the collection guides on different stacks with the different developer experiences (Appsody CLI or codewind+IDE).

I spotted https://github.com/kabanero-io/draft-guide-codewind-getting-started the other day and wondered if we were creating guides with too much overlap, but had no visibility of what the content plan was around Kabanero/codewind. This guide IMO is already too heavy, so adding Che there seems inappropriate.

If we still want to go ahead with our plan for collections, this issue could be used for Che when it's ready.

**Comment by marikaj123** [comment]
@ianpartridge - Is the content ready for Alan/Nate to review? If yes, please make them as reviewers to the PR.  Thank you.

**Comment by SueChaplain** [comment]
@marikaj123 I created this recently as I saw a gap. I'll be working on it at some point, but not for 0.2. There was noone asking for it for 0.2 and we don't have the resources to complete it in time. 0.3 will be a more reasonable target. I'm not sure why @ianpartridge was assigned. If I need some support from the dev team, I'll find someone to ask. Thanks

**Comment by SueChaplain** [comment]
Initial draft repo created and populated with a draft from Kye. Doc review required ahead of validation: https://github.com/kabanero-io/draft-guide-microprofile-eclipse-codewind/blob/master/README.adoc

**Comment by KyeMaloy97** [comment]
The draft has been checked over and approved by Sue, just needs to get through the last steps now.

**Comment by marikaj123** [comment]
@KyeMaloy97 - Is the issue ready to close?

**Comment by SueChaplain** [comment]
@marikaj123 - we need to apply changes identified by Alan and Nate from their review of the MicroProfile guide. I'm working through this.

**Comment by SueChaplain** [comment]
@alohr51 - do I need to do anything further for this to be published. I added "ready to publish" label. Thanks!

**Comment by KyeMaloy97** [comment]
Guide has been added to the site, so closing this issue 👍 

Avaiable at https://kabanero.io/guides/microprofile-eclipse-codewind
