### ISSUE TITLE
cross-check the Guides with Learning-Kabanero-101 site

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#105]
https://github.com/ibm-cloud-architecture/Learning-Kabanero-101

There is a site developed by Garage team that duplicates some of the info in the Guides.
We need to cross-check the two sources to be sure they are consistent.
Perhaps we can link to Learning-Kabanero-101 in the Guides.

See https://github.com/ibm-cloud-architecture/Learning-Kabanero-101/issues

**Comment by bschrammIBM** [comment]
from @ebullient ```
The Garage is required to produce this content: it’s part of their mission, and how they structure these as courses for their engagement so the content is similar, but the audience is a little different (and they will emphasize garage approach). I would definitely treat the Garage guides as source material for things we don’t have already have.
Just bear the bigger context (for them) in mind: https://ibm-cloud-architecture.github.io/deliverables/cloud-native.html
(in theory, we have content that fits within their outlines.. and they have content that would fit within ours.. but I don’t think the audience or delivery is necessarily the same. Tonally different, at a minimum)
```

**Comment by stephenkinder** [comment]
@ebullient @bschrammIBM I'm ok with enabling vendors to build, but this is an open-source project and it needs its own guides.  It is the vendor's responsibility to be consistent with the open-source project.  Also, internal links in public are generally considered bad form.

**Comment by bschrammIBM** [comment]
This is not an issue as garage site is not the official product doc.
