### ISSUE TITLE
Installation script instructions need embellishing

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#107]
@davco01a commented on [Mon Sep 23 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82)

On this page, in the `Installation` section:

https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html

I don't see any mention of copying and modifying:

https://github.com/kabanero-io/kabanero-operator/blob/master/config/samples/full.yaml

prior to running the install-kabanero-foundation.sh script

---

@mtamboli commented on [Mon Sep 23 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-534347246)

Step 3 (which is added recently) of the following doc assumes that the updates are being made to full.yaml. None of the Kabanero install docs talk about how this file is used.  https://github.com/kabanero-io/docs/blob/master/ref/general/collection-building.adoc

---

@bschrammIBM commented on [Tue Sep 24 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-534624267)

I opened https://github.com/kabanero-io/docs/issues/103 to track this update in the /docs repo.

---

@alohr51 commented on [Tue Sep 24 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-534655728)

@bschrammIBM is https://github.com/kabanero-io/docs/issues/103 a duplicate issue of this? We should try to not duplicate issues. You can move/transfer this issue to the docs repo if that was your goal (bottom right of this issue)

---

@kaczyns commented on [Tue Sep 24 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-534663756)

This page:
https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html
reads to me like a basic getting started / install page.  I think that if we try to talk about modifying the default kabanero yaml here it will be confusing for the people that just want to get started.  Maybe we could say at the end of the install script section something like:

"This will install Kabanero with default settings using the default collections (link to collections).  If you would like to use a different set of collections, see here (link to doc about how to curate the collection)".

That seems like a compromise to me between keeping the page simple for new folks, but also reminding experienced users that they have some editing to do if they want to deploy an Nth Kabanero using collections that they've already curated.

---

@mtamboli commented on [Tue Sep 24 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-534685404)

@kaczyns I agree with your comment above to keep the default install simple. But my understanding is that you still need to do some customization (full.yaml git updates for security) before installing Kabanero to be able to use Kabanero CLI later. Can that be done easily later if user wants to use Kabanero CLI? 

---

@kaczyns commented on [Tue Sep 24 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-534710633)

@mtamboli My understanding is that you can't use the CLI until you've cloned and curated the collections, because Champ will be unable to add himself as an admin to the kabanero-io hosted collections.  I don't think there is a reason to customize the configuration (full.yaml) until Champ has curated the collections, and at that time the following things need to be updated:
1) URL of the collection
2) Github org that the admins for the collection are in
3) Github team(s) that admin the colleciton
4) API URL of the github where the org/teams are

It's pretty easy, the user can either edit the `Kind: Kabanero` that the install produced, on their cluster, or they can delete it and create a new one using the full.yaml as a model.  Editing is as simple as `oc edit kabanero kabanero` (the default name) and then a text editor pops up and they change the url, etc.  Or they could edit it in the OKD console.

---

@mtamboli commented on [Tue Sep 24 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-534731334)

That helps! So it is matter of getting the documentation at the appropriate place. So collection curation and GitHub setup as part of that is a pre-req for Kabanero CLI? So Install doc can just provide links to those as you mentioned. 

---

@davco01a commented on [Thu Sep 26 2019](https://github.com/kabanero-io/kabanero-foundation/issues/82#issuecomment-535530781)

@mtamboli @kaczyns It may be simple to `oc edit kabanero kabanero`, but agree with Monica in lieu of clear, sequenced documentation on cloning the index.yaml, copy and modifying full.yaml, setting up git teams and members located in one central, relevant place, it will be a mystery to consumers who want to be able to actually use the functionality of the Kabanero CLI

**Comment by bschrammIBM** [comment]
@alohr51 I copied this issue to the /docs repo and will close the dup.

**Comment by davco01a** [comment]
Plan should be keep main install page the same with a hyperlink to a child page that details this config for a cloned Champ collection

**Comment by mtamboli** [comment]
I am not sure if we need new issue for the page which will be linked from install page. I see Install page providing a link to another page which will list these 2 scenarios:

1. Using Kabanero CLI with existing/default collection
My understanding is that you still need to make some changes too full.yaml for collection (on existing instance) file but do not need to build new collections for this.

2. Curate Collections: This will include instructions on forking the collections, making changes, testing locally, Testing manually with pipeline, creating a release for collection, using this new collections with Kabanero instance.
@kaczyns @davco01a Please provide your feedback if I am understanding these 2 scenario correctly.

**Comment by kaczyns** [comment]
@mtamboli I don't see the value in using the CLI for the default collections.  Could you explain why someone would want to do this?

For 2) yes I agree with you.

**Comment by mtamboli** [comment]
@kaczyns Option 1 is if the user has already installed Kabanero and later decide to update collection and  use CLI. I would imaging this is a valid path and need to be documented as well?

**Comment by marikaj123** [comment]
@kaczyns - who can help with documenting the path described above by Monica?  Would it be CLI team?

**Comment by kaczyns** [comment]
@marikaj123 Monica and I have been talking about this doc, I have the following PRs which I hope will address the issues she raised here:
https://github.com/kabanero-io/docs/pull/127
https://github.com/kabanero-io/docs/pull/123

If not, please add specifically what should be added/enhanced to resolve this issue.  I don't think it's valid to set up the CLI until Champ has curated the collections (after installing), but we've included a link to the Kabanero CR reference in case someone wants to.  And we've expanded the doc for the curating collections page with more specific information about setting up the CLI.  @mtamboli

**Comment by marikaj123** [comment]
@mtamboli - Please inform us in case more info is required.

**Comment by kaczyns** [comment]
#127 and #123 have merged.  Please open a follow-on issue if more updates are required.  Thanks!
