### ISSUE TITLE
Missing mention to required role for accessing pipeline information in tekton dashboard

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/docs#109]
The installation page at
https://github.com/kabanero-io/docs/blob/master/ref/general/installing-kabanero-foundation.adoc
indicates that people can "Make detailed pipeline changes by accessing the Tekton dashboard", but it does not indicate the required role for the user.

After reading through the deployment files, I believe this is the correct role, since it allowed me to see the pipeline information:

`oc policy add-role-to-user tekton-dashboard-minimal <userid>`

This information would be helpful in that page.

**Comment by marikaj123** [comment]
Close after publishing

**Comment by jantley-ibm** [comment]
@nastacio based on the input from @mnuttall I think we should close this one as invalid.  If we want to make different updates, let's open a new issue.

**Comment by nastacio** [comment]
I agree with closing. I think part of the confusion was also introduced by https://github.com/tektoncd/dashboard/issues/528, which was opened later.

It is possible that I have verified the "solution" here on a different web browser than Firefox and gotten the impression the role assignment fixed the issue.
