### ISSUE TITLE
Collection building and Travis

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/docs#112]
The https://github.com/kabanero-io/docs/blob/master/ref/general/collection-building.adoc document glosses over Travis setup. For example, it doesn't explain how Travis should be setup with DockerHub credentials. Maybe the document shouldn't even talk about Travis or creating releases if the topic is about "building collections locally".

**Comment by mingcyu** [comment]
Sue to look into leveraging guide to convey the information

**Comment by SueChaplain** [comment]
Hi @jgawor - we plan to replace this topic with a guide, which is currently in review:
https://github.com/kabanero-io/draft-guide-working-with-collections

The guide is aimed at Champ, for managing those parts of the collection that relate to stacks, not pipelines. There is another guide being written that covers "Working with pipeline".

The working with pipelines guide is more aimed at Todd - would that be an appropriate guide to cover "how Travis should be setup with DockerHub credentials."??

**Comment by jgawor** [comment]
Well, that might work but the new document is already pretty long. And I don't see how this works end to end. I think we might need a document (that's actually verified) that works with github.com and another one for GitHub Enterprise. One that uses DockerHub with some custom organization and another one that uses internal registry.

**Comment by SueChaplain** [comment]
I think there is scope to create guides for these areas. Who would be the best person to sketch out the user flows for these scenarios?

**Comment by mtamboli** [comment]
@SueChaplain I think it would be great to get help from collections team to make sure that we have documentation for various flows for collections.

**Comment by marikaj123** [comment]
@SueChaplain - Is this for release-0.3? If yes, then please add the label and let us know if we need to engage the collection team for help.

**Comment by SueChaplain** [comment]
@marikaj123 - I don't think this will be possible for the 0.3 release. I'm not even sure what the guide should contain. Per comment 2 day ago: 

>Who would be the best person to sketch out the user flows for these scenarios?

**Comment by bhatsuresh** [comment]
@marikaj123 stuff like this should go back to the architect to delegate or assign to someone in that component area. In this case it sounds like Collections...and if I am guessing correctly that would either be Ian

**Comment by marikaj123** [comment]
@bhatsuresh - I am asking if the issue requires release 0.3.0 for priority reasons.

**Comment by mingcyu** [comment]
@groeges @kvijai82 Which release should this be included in?

**Comment by mingcyu** [comment]
Since Collections are being replaced by Stacks this is no longer valid
