### ISSUE TITLE
Add the namespace info to Create secrets step

### ISSUE THREAD

**Issue by wtistang** [kabanero-io/docs#128]
In the instruction to create a GitHub secret of "Connecting Kabanero to GitHub with Tekton Webhooks", the kabanero namespace should be used, but that info is missing in the instruction.

**Comment by stephenkinder** [comment]
@bschrammIBM we need to clarify the instructions.

**Comment by dmuelle** [comment]
PR for this update- https://github.com/kabanero-io/docs/pull/131
