### ISSUE TITLE
specify namespace when creating the service account kabanero:appsody-sa

### ISSUE THREAD

**Issue by csantanapr** [kabanero-io/docs#14]
In the docs
https://github.com/kabanero-io/docs/blob/master/ref/general/kabanero-foundation-setup.adoc

The command 
```
kubectl apply -f appsody-service-account.yaml
```

Should have the `-n` to be sure the `sa` is created in the correct namespace and not in the current context namespace which it can be `default` or `myproject` 

In addition since the doc is using `oc` it should use `oc` instead of `kubectl`

I proposed the command should be
```
oc apply -f appsody-service-account.yaml -n kabanero
```

**Comment by alohr51** [comment]
looks like this is resolved in the newer version https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html
