### ISSUE TITLE
Request new "Overview" category

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/docs#141]
We have a Kabanero overview, introduced in issue #41 and hosted currently as a guide in kabanero.io (https://kabanero.io/guides/overview/) . 

That is not a guide in terms of guiding the user towards execution of steps and achievement of a goal, but rather an overview we wanted in the navigation tree of the "docs" portion of the site itself: https://kabanero.io/docs/

At the same time, it is also neither an "installation" (for obvious reasons) or a "reference" (since references are suggestions for further learning) . This guide is something people must read in order to understand how all Kabanero pieces fit together.

In that sense, I suggest a new "Overview" category, for content that is meant to educate the user on conceptual topics, such as this architectural overview.

Now that I just wrote "conceptual", I think "Concept" is a good category instead of "Overview" if others feel "Overview" is too specific.

**Comment by alohr51** [comment]
Overview category is in place on kabanero.io
