### ISSUE TITLE
Add more details about the subdomain parameter using nip.io

### ISSUE THREAD

**Issue by csantanapr** [kabanero-io/docs#15]
Provide more details about using nip.io when working locally 

For example for minishift you can tell user to use the ip address from the ocp console ui
```
oc console
```
Locally the browser will open for example `https://192.168.64.4:8443/console`
Use this value of the ip address `192.168.64` and append `.nip.io` this will be the value to use for subdomain
```
openshift_master_default_subdomain=192.168.64.4.nip.io ./install-kabanero-foundation.sh
```

**Comment by jantley-ibm** [comment]
Needs to be mentioned in install docs

**Comment by marikaj123** [comment]
@jantley-ibm - Does the issue contain what is needed for the ID team to provide the 'ID-reviewed' label?

**Comment by jantley-ibm** [comment]
@csantanapr is this sufficient, as the third bullet in Install step 5 on https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html:
* If using a wildcard DNS such as nip.io, append it to the subdomain: `openshift_master_default_subdomain=<MY_OPENSHIFT_MASTER_DEFAULT_SUBDOMAIN>.nip.io ./install-kabanero-foundation.sh`

**Comment by csantanapr** [comment]
@jantley-ibm yes is sufficient
