### ISSUE TITLE
Teams list in Kabanero should be yaml list not comma separated

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#158]
Teams list in Kabanero should be yaml list not comma separated

**Comment by davco01a** [comment]
e.g.

correct:

```
teams: 
  - collection-admins
  - admins
```

incorrect:

```
teams: collection-admins,admins
```

**Comment by davco01a** [comment]
see bottom of:

https://kabanero.io/docs/ref/general/kabanero-cr-config.html

**Comment by davco01a** [comment]
two docs need to be changed:

 collection-install.adoc and kabanero-cr-config.adoc

**Comment by alohr51** [comment]
@jantley-ibm when the PR is merged the issue should close, you can add the `closes #xxx` keyword to your PR description so when it's merged, GitHub will automatically close issues for you so we don't have to remember to do that step.

https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
