### ISSUE TITLE
example doesn't work out of the box imagePullPolicy set to Always

### ISSUE THREAD

**Issue by csantanapr** [kabanero-io/docs#16]
In the docs https://github.com/kabanero-io/docs/blob/master/ref/general/kabanero-foundation-setup.adoc#setting-up-the-example-appsody-pipeline 
 they refer to use the following example https://github.com/appsody/tekton-example.git

The knative service yaml specify imagePull
https://github.com/chilanti/appsody-test-build/blob/master/appsody-service.yaml#L11-L12
```
image: dev.local/appsody-build-test
imagePullPolicy: Never
```
Having any string for `image` is ok and using `Never` makes sense when working with loading the image locally not using a remote registry.

But the example is using tekton and pushing to a registry, having `Never` the image will never be downloaded and the Pod fails to run.

Maybe it would be good to have the example on the this docs repo.

I fix the problem by setting the imagePullPolicy to `Always` or not being presented should also work.

**Comment by stephenkinder** [comment]
@csantanapr is this still a problem?  This looks like it is corrected.

**Comment by marikaj123** [comment]
@jantley-ibm - Does the issue contain what is needed for the ID team to provide the 'ID-reviewed' label?

**Comment by csantanapr** [comment]
I'm using kabanero pipelines on OpenShift and don't see this problem anymore
