### ISSUE TITLE
Add information about mustgather script

### ISSUE THREAD

**Issue by jantley-ibm** [kabanero-io/docs#160]
Need doc on the kabanero site regarding using the mustgather script

https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/mustgather/kabanero-mustgather.sh

**Comment by mingcyu** [comment]
Content should go some where near the troubleshooting page?

**Comment by marikaj123** [comment]
@alohr51 - Andrew, can you help?

**Comment by alohr51** [comment]
What do you need help with?

**Comment by jantley-ibm** [comment]
@alohr I think all I need is an example of the actual command that runs all of the scripts, and the location(s) where the data is stored.

**Comment by alohr51** [comment]
@jantley-ibm I would see who wrote the script and ask them.

**Comment by jantley-ibm** [comment]
Done, working on draft now
