### ISSUE TITLE
Need cookbook for GIT team creation and adding members

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#163]
Need cookbook for GIT team creation and adding members

**Comment by davco01a** [comment]
add to: https://kabanero.io/docs/ref/general/kabanero-cr-config.html

**Comment by mingcyu** [comment]
@davco01a Who can ID Team work with gather content?

Consider making this a guide?

**Comment by mingcyu** [comment]
@davco01a Is this needed for 0.4?

**Comment by davco01a** [comment]
yes, @ralanlittle wants it

**Comment by davco01a** [comment]
they can work with me
