### ISSUE TITLE
Document new kAppNav logging/trace actions for OpenLiberty for 11/15/19

### ISSUE THREAD

**Issue by chirp1** [kabanero-io/docs#166]
Write / edit the documentation for Kapp Nav

Determine the topics and the architecture for the topics in the navigation. Review the topics and architecture with Pam.

    Richard: List the Kapp Nav topics here:
    Edit or create these Kapp Nav topics.
    Ensure that development (Chris, etc) tests task topics by having them reading the steps in the task topics and following the steps read.

**Comment by marikaj123** [comment]
@Rwalls1 - Do you need to include a developer from kAppNav to help with the content for this issue.

**Comment by Rwalls1** [comment]
@marikaj123 Yes, I think I'll be working with Chris Vignola.

**Comment by marikaj123** [comment]
@cvignola needs to have permission to show as assignee.

**Comment by marikaj123** [comment]
Hi @Rwalls1 - Any status update on this issue?

**Comment by Rwalls1** [comment]
@marikaj123 These are comments I've received from Chris, I'll update the issue to reflect this info: 
Document new logging/trace actions for OpenLiberty:
OpenLiberty containers send logs to EFK stack and optionally expose metric data for gathering by Prometheus. New actions use Kibana/Grafana dashboards to display these data.

OpenLiberty metrics is off by default and must be enabled both in the image as well specify a label to enable the metric menu option in kAppNav.

EFK (for workloads) and the metrics stack (Prometheus/Grafana) are not installed on OpenShift by default. Kabanero provides documentation for how to do that. This doc should point to that Kabanero doc as a pre-req.

**Comment by Rwalls1** [comment]
@marikaj123 Doc blocked waiting for Kabanero guide to get published: https://github.com/kabanero-io/guide-app-logging

**Comment by marikaj123** [comment]
@Rwalls1 - Guides they do have their own schedule.  @alohr51 - Any suggestion?

**Comment by alohr51** [comment]
app logging guide is published https://kabanero.io/guides/app-logging/

**Comment by mingcyu** [comment]
@alohr51 Can you confirm if this is the guide that was published and can we close this issue if so?

**Comment by alohr51** [comment]
@mingcyu see comment above https://github.com/kabanero-io/docs/issues/166#issuecomment-555250067

**Comment by mingcyu** [comment]
@Rwalls1 The blog that was blocking this is published, so we should be able to make progress now

**Comment by Rwalls1** [comment]
The following drafts are available here for documenting the kAppNav logging/trace actions: 
https://github.com/kappnav/README/blob/master/liberty-action-view-metrics.md
https://github.com/kappnav/README/blob/master/liberty-action-view-kibana-logs.md

**Comment by Rwalls1** [comment]
The documentation for this issue has been completed here: https://github.com/kappnav/README/blob/master/liberty-action-view-metrics.md
https://github.com/kappnav/README/blob/master/liberty-action-view-kibana-logs.md
I will close the issue.
