### ISSUE TITLE
Remove content duplication: Modifying the default Kabanero collection

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#167]
Doc page: https://kabanero.io/docs/ref/general/collection-building.html was created from https://github.com/kabanero-io/collections/blob/master/README.md to plug a gap.

The following guide is in review and provides a learning journey for working with collections that incorporates this content: https://github.com/kabanero-io/draft-guide-working-with-collections

Proposed action when this guide completes review and is published on the website (expected this week):

- [x] Remove https://kabanero.io/docs/ref/general/collection-building.html
- [x] Remove duplication from https://github.com/kabanero-io/collections/blob/master/README.md, pointing to the new guide.

@mtamboli - FYI, any remaining concerns?

**Comment by marikaj123** [comment]
@SueChaplain - According to the collection team modified the readme to point to the guide to remove any dup of info.  Let us know if you need any help to complete this issue.

**Comment by SueChaplain** [comment]
PR raised to remove the docs page: https://github.com/kabanero-io/docs/pull/184
PR merged but I believe changes won't be live until the next release (0.3.0)
I can see that @groeges has completed the changes in the collections repo - thanks!

@marikaj123 - I believe we can close this issue now, unless you want to leave it open until the release goes out and the Docs pages are refreshed? If not, please feel free to close.

**Comment by marikaj123** [comment]
@alohr51 - Pease close after the docs are published. Thank you.

**Comment by alohr51** [comment]
@marikaj123 this should close when the PR associated with it is merged.

**Comment by SueChaplain** [comment]
That PR was merged. So closing this issue.
