### ISSUE TITLE
Guide for Jenkins integration with Kabanero

### ISSUE THREAD

**Issue by Charlotte-Holt** [kabanero-io/docs#173]
This guide was already written by @dewan-ahmed, and it is in the review process. It's currently located at https://github.com/kabanero-io/draft-guide-jenkins-integration-with-kabanero.

**Comment by anneqm** [comment]
See issue #66

**Comment by Charlotte-Holt** [comment]
Published at https://kabanero.io/guides/jenkins-integration-with-kabanero/
