### ISSUE TITLE
OCP4.2 Install script is located in the ocp42 folder. Update Install Doc

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/docs#177]
To help separate the OpenShift vs. OKD install experience, we created a folder for OCP 4.2 to hold the new install example scripts.  When 0.3.0 is released, we need to make sure the correct links for Try It! are pointing at the right scripts.

https://github.com/kabanero-io/docs/blob/master/ref/general/installing-kabanero-foundation.adoc needs to be updated to point to the 0.3.0 way of installing kabanero

**Comment by SueChaplain** [comment]
@mingcyu - some work to assign in the docs team, maybe to someone who is familiar with the material already there.

**Comment by kaczyns** [comment]
@stephenkinder The install script actually moved to the kabanero-operator repository.  It's attached to the kabanero-operator release.  The install instructions in kabanero-foundation reference this now. and I'll be updating the install docs to reference this as well.

Please let Dan and I know if this new arrangement is unacceptable.
