### ISSUE TITLE
Guide for creating a new Pipeline and adding to Kabanero Collection

### ISSUE THREAD

**Issue by jxadro** [kabanero-io/docs#180]
I think it would be good to have a clear and "deep" understanding a guide or lab for creating from scratch a new stack and a new tekton pipeline and make them work together.

**Comment by bschrammIBM** [comment]
Should this wait until after kabanero release 0.4 on Dec 2? there are many updates to pipelines contained in that release.

**Comment by stephenkinder** [comment]
@jxadro  I think we'll wind up with a Kabanero pipeline and pipeline task library, and a default best-practice set of pipelines that are burned into the default collection.  I agree we should have a guide for updating pipelines, and I think we can work on this as part of an upcoming Kabanero release.

**Comment by mingcyu** [comment]
Closing as a duplicate
