### ISSUE TITLE
Add ability to order subtopics in Docs

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#191]
With the next release we will have 4 categories of Docs: Overview, Installation, Configuration, and Reference. Currently there is no way of ordering the topics within these categories, which means that we cannot create a reading order that makes sense.

E.g. 

Configuration: (next release)

![config](https://user-images.githubusercontent.com/18395037/68393093-23aaaf00-0163-11ea-8f04-6e409e596d66.png)

**Configuring a Kabanero CR instanced ** should come before **Configuring a Kabanero CR instance to use an alternative collection repository. **

- How is the current order established?

**Comment by marikaj123** [comment]
@kidus60 - Please provide us with the status on this issue?

**Comment by kidus60** [comment]
@marikaj123 I have submitted a pull request for the issue on both the website and docs repo, just waiting on a review.

**Comment by SueChaplain** [comment]
@alohr51 - can this be closed now?

**Comment by alohr51** [comment]
@SueChaplain yup
