### ISSUE TITLE
Write a Guide for "Using the NodeJS Collection"

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#204]
Extending issue https://github.com/kabanero-io/docs/issues/48, to break out issues for each of the Node.js collections.

>Today, we have 5 collections and we don’t even have one guide per collection, which was the MVP Alan & I set for 0.1

This issue is to write a guide for the base Node.js collection.

- guide must be identical to the MicroProfile and Spring Boot guides already published, replacing the elements unique to this collection.

**Comment by mingcyu** [comment]
Sue is working with local team to code the sample, no need to talk to Collection's team at the moment

**Comment by SueChaplain** [comment]
New repo created: draft-guide-collection-nodejs with ID team and Website team permissions.
Created an initial draft, which gets as far as "Creating and updating your application". Pushed to repo.

@davehobbs - ready for sample app creation.

**Comment by SueChaplain** [comment]
This guide is now ready for review. PR raised for review by @ralanlittle or @nateziemann .

**Comment by SueChaplain** [comment]
Ready to publish.

**Comment by SueChaplain** [comment]
Guide published. Closing
