### ISSUE TITLE
Write a Guide for "Using the NodeJS LoopBack Collection"

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#205]
Extending issue https://github.com/kabanero-io/docs/issues/48, to break out issues for each of the Node.js collections.

>Today, we have 5 collections and we don’t even have one guide per collection, which was the MVP Alan & I set for 0.1

This issue is to write a guide for the Node.js **LoopBack** collection.

- guide must be identical to the MicroProfile and Spring Boot guides already published, replacing the elements unique to this collection.

**Comment by mingcyu** [comment]
Sue is working with local team to get working sample code

**Comment by SueChaplain** [comment]
Created new repo for guide: draft-guide-collection-nodejs-loopback and set team permissions for ID and website.
Pushed an initial draft of the guide.

- project layout needs further descriptions
- Changes required for "Creating and updating your application" and later sections, when we have sample source.

@davehobbs  - ready for sample source.

**Comment by SueChaplain** [comment]
Guide published. Closing.
