### ISSUE TITLE
Evaluate common strings used across Docs and Guides

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#212]
Discover which docs (and guides) have references to Kabanero versions and require updates each release:

- can we replace these references with more generic terms. E.g. `<latest version>` plus an example string like `https://github.com/kabanero-io/collections/releases/download/0.3.0/kabanero-index.yaml`, where `<latest version>` is 0.3.0
- how many other references to versions are we using across the Docs, and how many are common vs unique

Evaluation will help drive decisions about how we handle this for 0.4.0

**Comment by jantley-ibm** [comment]
We should also note if there are instances of strings that should not be automatically updated each release -- for example, perhaps a particular version number indicates the last tested release of something.

**Comment by SueChaplain** [comment]
List of topics that contain version specific information and proposed action:

1. **Installing Kabanero Foundation**: 1 instance that has to stay for now (In 0.3.0 we are using OCP instead of OKD), 3 further instances of version 0.3.0 where we could substitute `<version>` with an explanation for how to find the latest version info.
2. **Uninstalling Kabanero Foundation**: 1 instance where we could substitute `<version>` as above.
3. **Configuring a Kabanero CR instance to use an alternative collection repository**: Example configs contain version-specific info, which we could modify as in (1) and (2).
4. **Configuring a Kabanero CR Instance**: Reference to `semver` and an example 0.2.0. Provide a link to `semver` for readers who are not familiar with the notation and replace 0.2.0 with x.y.z. Topic also contains default collection URL for Kabanero 0.1.2. Should probably reference the organisation collection hub instead, with an embedded `<version>` variable and explanation. Lastly, some examples with very old v0.1 format strings, which have changed. We should update the examples with templates instead, where we reference variables and provide explanations.
5. **Working with Collections in VS Code or Eclipse**: In another issue we are proposing to remove this topic as it duplicate info in a guide, so the version info won't need updating.
6. **Kabanero CLI** : Contains some sample template output, which might have changed. Should update at the very least.

Conclusion: I think we can easily minimize the use of specific version strings to avoid updating topics every release.

**Comment by SueChaplain** [comment]
Created PR https://github.com/kabanero-io/docs/pull/229 to address the Foundation install/uninstall topics.

**Comment by mingcyu** [comment]
Use this issue to create a "release" issue for each release so we know what we need to manually change so that text from code blocks would cease to function. This is a temporary solution until we can find a more technical/automated solution

How about adding a version= latest to help with versioning issue 

Sue suggest that we bring this up to wider group (kabanero-scrum) and will start it next week in the slack channel

**Comment by mingcyu** [comment]
Will need to include this as part of documentation revision effort

**Comment by mingcyu** [comment]
Closing as we added this as an additional item to #267 and #266
