### ISSUE TITLE
The version for the existing docs release (1.0.0) doesn't match Kabanero current release.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/docs#22]
We are in the midst of trying to manually produce the 0.0.2 release of Kabanero until we have a formal release process defined.   I don't think we want to define a 1.0.0 release because that implies a level that is GA.   We likely need to actually delete the 1.0.0 release that is defined in this repository, and we should replace it with a 0.0.2 when we are ready to cut the release.

**Comment by alohr51** [comment]
[docs repository first release is now v0.0.2](https://github.com/kabanero-io/docs/releases/tag/v0.0.2)
