### ISSUE TITLE
Remove content duplication: Working with Collections in VS Code or Eclipse

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#222]
https://kabanero.io/docs/ref/general/codewind-kabanero-collections.html

Early topic can now be removed as we have more than one guide that covers working with collections in IDEs. For example:

- [Getting Started with Codewind and Kabanero](https://kabanero.io/guides/guide-codewind/)
- [Developing with Kabanero Collections in your Eclipse IDE](https://kabanero.io/guides/microprofile-eclipse-codewind/)

Action:

- Update https://kabanero.io/docs/ref/general/installing-dev-tools.html to point to guides rather than this topic
- Remove this topic

**Comment by SueChaplain** [comment]
@Jhschube - I looked in to the history and identified this as a contribution you made. Are you happy for this content to be removed please? Nothing wrong with it - it served its purpose well whilst other content was pulled together.

**Comment by mingcyu** [comment]
Decision on call 12/2 to remove content

**Comment by SueChaplain** [comment]
PR: https://github.com/kabanero-io/docs/pull/230
