### ISSUE TITLE
Remove content duplication: Appsody Hello World on Codewind

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#223]
https://kabanero.io/docs/ref/general/hello-world-appsody-codewind.html

Early topic, partly duplicated by Try It!, but we also a couple of guides available that provide more extensive information:

- [Getting Started with Codewind and Kabanero](https://kabanero.io/guides/guide-codewind/)
- [Developing with Kabanero Collections in your Eclipse IDE](https://kabanero.io/guides/microprofile-eclipse-codewind/)

Action:

- Check that this topic is not linked to from Try It! or elsewhere on the site
- Remove this topic

**Comment by SueChaplain** [comment]
@Jhschube - another early topic. This one actually a little out of date as the Appsody extension now gets installed by Codewind. Anyway, proposing to remove this now that we have guides covering codewind in more detail. Please confirm you are ok with this.

**Comment by mingcyu** [comment]
Decision made on call to remove as information is duplicated and incorrect

**Comment by SueChaplain** [comment]
PR: https://github.com/kabanero-io/docs/pull/230
