### ISSUE TITLE
Update tekton-webhooks doc to add instruction on how to delete webhooks

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/docs#225]
Add section to document 'https://kabanero.io/docs/ref/general/tekton-webhooks.html" to describe how to delete previously created webhooks.   

This documentation is needed because when the next version of Tekton Dashboard and Webhooks extension is released and picked up by Kabanero.io, existing customers on the previous version must delete existing webhooks before uninstalling or upgrading the previous release, and then recreate webhooks afterwards.

**Comment by dmuelle** [comment]
Hi @anneqm - who can provide the technical information for removing a webhook? I'll do the ID work but I need a draft of the process. This subject isn't covered in the [Webhooks getting started](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md)
Thanks!

**Comment by dmuelle** [comment]
@anneqm PR for this update- let me know if it needs changes
https://github.com/kabanero-io/docs/pull/246

one minor thing to confirm- you select a webhook from the list b y clicking a box beside the webhook name? That's what it looks like but since it's already selected in the screenshot that I had I just wanted to confirm that- Thanks

**Comment by anneqm** [comment]
@dmuelle Yes, as we discussed, that's exactly right. I reviewed and agree with the associated PR https://github.com/kabanero-io/docs/pull/246 but am unable to approve it.   Who else can approve?

**Comment by dmuelle** [comment]
@jantley are you authorized to approve this PR? It's SME approved but if you think it needs anything else from an ID perspective just let me know. Adds a section for deleting a webhook...

https://github.com/kabanero-io/docs/pull/246

**Comment by dmuelle** [comment]
Ok- thanks @jantley-ibm , changes are merged

**Comment by dmuelle** [comment]
@anneqm does this need anything further or are we clear to close this issue?

**Comment by anneqm** [comment]
@dmuelle I think we are fine to close this issue.  The updated guide has been published with the new information.  https://kabanero.io/docs/ref/general/configuration/tekton-webhooks.html  Thanks!
