### ISSUE TITLE
Create a guide for using Nexus Repository with Appsody

### ISSUE THREAD

**Issue by deboer-tim** [kabanero-io/docs#233]
Create a guide showing how to customize Appsody stacks with Maven and NPM content to integrate with Nexus Repository.

Draft content is in box: https://ibm.ent.box.com/notes/566378512827?s=hxk1zlcfh3l2210on98e74qgwk7gjwl6

**Comment by bschrammIBM** [comment]
Email from @deboer-tim 
I will ask him to create the text in Markdown in a repo called draft-<etc> to help move the process along. 
@jantley-ibm @mingcyu Can you provide a date for when this Guide can be published (once it is in Markdown?)

```From: Tim deBoer/Toronto/IBM
To: Barbara Schramm/US/IBM@IBM
Cc: Robert Taniwa/Toronto/IBM@IBMCA
Subject: Re: Directions for creating a Guide to be published on kabanero.io
Date: Fri, Dec 6, 2019 12:06 PM
 
Hi Barbara,
 
How long does the process typically take from here, and what parts can we do to help or move things along? The Sonatype relationship is getting a fair bit of exec visibility at the moment so I'd like to keep this moving along and published as soon as possible, just let us know when there's anything we can do.
 
Thanks,
Tim deBoer
IBM Cloud Developer Experience, Senior Technical Staff Member
(905) 413-3503 | deboer@ca.ibm.com```

**Comment by bschrammIBM** [comment]
@sghung is going to start the process by following the instructions here: https://github.com/kabanero-io/draft-guides-template and creating the Guide in Markdown.

**Comment by jantley-ibm** [comment]
@deboer-tim the process for creating, polishing, reviewing and approving guides is here: https://apps.na.collabserv.com/wikis/home?lang=en-us#!/wiki/a5685d39-296b-43d3-99e9-5f947788ace7/page/f82fbde8-e182-4307-901f-1483fb6f0cb0/version/4163d610-c69b-4a71-882b-141226492074

Guides can be published to production whenever final approval is received, they are not tied to releases

**Comment by csantanapr** [comment]
I review the box note draft the NPM/node.js portion and here is my feedback.
>Draft content is in box: https://ibm.ent.box.com/notes/566378512827?s=hxk1zlcfh3l2210on98e74qgwk7gjwl6

Review comments (NPM portion only):
The guide is not using best practice to protect secrets/passwords.

The .npmrc file containing secrets and maybe sensitive (ie IP) config is leaking in two places.
1. checking the .npmrc contents with the actual values into git
2. the final container image in production will have a copy of fhe file .npmrc 

The file .npmrc file contents is only required in 2 places.
1. Developers laptop/desktop/IDE: the content of .npmrc in the root of the template/app and this file should be .gitignore to avoid sharing it by mistake. One way to share the file content is basically checking a .npmrc templetized, including the .gitirnoge and in the readme of template have instructions 
to have the developer to contact admin or follow instructions to get the hostanme and password to use. 
2. During container image creation (ie buildah/kaniko). During container build using Dockerfile take advantage of multistage build, and the .npmrc file can be created using the config and secret values from the environment for example tekton step variables using configmap and secrets, only the build steps/image should have the .npmrc, but this file should NOT be copy to the final runtime image only the node_modules

Following this guides, the secrets and sensitive config can be avoided from being leak.

**Comment by sghung** [comment]
@csantanapr thank you for your comment, I have addressed the issue in the NPM scenario and the credentials can be added by the developer and won't be in the final runtime image.

For the Maven scenario, I have stopped the final runtime image from having the settings.xml. The settings.xml cannot be removed from the inner loop development stage as Maven is called many times and requires this settings.xml to be present. Unless the stack is simplified (i.e. the architect writes their own stack instead of copying the appsody default stack), there's no way around that as far as I can see.

**Comment by sghung** [comment]
The PR is ready for review: https://github.com/kabanero-io/draft-guide-nexus-repository-integration-with-appsody/pull/1

**Comment by sghung** [comment]
I have added Alan Little and Nate Ziemann as reviewers. Thanks to Andrew Lohr for the original review. I will followup with both in the next couple of days.

**Comment by jantley-ibm** [comment]
closing as completed
