### ISSUE TITLE
CLI docs do not warn about incompatible versions of the cli pod

### ISSUE THREAD

**Issue by henrynash** [kabanero-io/docs#240]
For users wanting to install the kabanero CLI, the instructions are here: https://github.com/kabanero-io/docs/blob/master/ref/general/reference/kabanero-cli.adoc

However, there is no discussion/warning that the CLI major version must match the version of the cli pod running.  For instance, the IBM CP4A uses kabanero 0.2.x, but references the standard kabanero docs - which imply the best thing is to download the latest CLI. The 0.3.0 version of the CLI does not work agains a 0.2.x cli pod.

The cli docs should make this clear (and perhaps have instructions on how to check what version of the cli pod you are running)

**Comment by jantley-ibm** [comment]
@davco01a could you comment and/or suggest changes to doc (in particular, the comment in the last sentence above)?  I can make the actual updates -- thanks

**Comment by davco01a** [comment]
covered bye https://github.com/kabanero-io/kabanero-command-line/issues/155
