### ISSUE TITLE
clarify there are 2 different ways to install kabanero in install doc

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/docs#256]
Right now the install doc shows a scripted installation and a manual installation. On quick glance the format of the doc looks like you need to do both.

I suggest expanding on or changing the "_Alternatively, the install can be performed manually._" sentence in the [intro of installation section](https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html#installation) so that it:
1. Explicitly states there are 2 ways to install: the scripted way, or the manual way. 
1. Suggests using the scripted install over the manual install.

**Comment by jantley-ibm** [comment]
Fixed in #258 
Let me know if you think more is still needed.  I tried to downplay the manual install over the scripted, but I still am not comfortable making recommendations in technical doc.

**Comment by alohr51** [comment]
@jantley-ibm which PR in that issue is it? I'm having trouble finding it since that issue looks like its for guide updates.

**Comment by jantley-ibm** [comment]
@alohr51 see https://github.com/kabanero-io/docs/pull/259/files
