### ISSUE TITLE
0.5.0 Tekton trigger changes not reflected in establishing a webhook.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/docs#257]
There were changes related to Tekton triggers made in 0.5.0 that do not have documentation reflected.  The webhooks established before 0.5.0 will no longer work, they need to be reestablished.  There are differences in the way webhooks are established (requiring Tekton templates and bindings).  

https://kabanero.io/docs/ref/general/configuration/tekton-webhooks.html

**Comment by anneqm** [comment]
In moving to this release of kabanero, previously established webhooks will need to be removed, and then recreated. Note the how to delete webhooks was already added to the document in advance of this release. 
In addition, consider working in links to https://github.com/tektoncd/triggers/tree/v0.1.0/docs#tekton-triggers and perhaps https://github.com/tektoncd/pipeline/tree/v0.8.0/docs#tekton-pipelines in the sentence
>Your Kabanero installation includes an instance of the Tekton Dashboard with the Webhooks Extension installed.

**Troubleshooting:** Suggested addition to https://github.com/kabanero-io/kabanero-pipelines/blob/master/Troubleshooting.md:
>Failed to create webhook, error returned was : Could not find the required trigger template or trigger bindings in namespace: tekton-pipelines. Expected to find: tutorial-pipeline-template, tutorial-pipeline-push-binding and tutorial-pipeline-pullrequest-binding

It occurs when the user selects a Pipeline that doesn’t have  the associated TriggerTemplate and TriggerBindings when creating a Webhook in the extension.
We could possibly link this to instructions and/or more details about how each Pipeline must have a number of Triggers resources for the Webhooks Extension to work properly, such as described here: https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md#pipeline
> Select the Pipeline in the target Namespace from which a PipelineRun (and accompanying PipelineResources) will be created, as described in the section 'What does the Tekton Dashboard's Webhooks Extension do?', above. Note that you need to have related Tekton Trigger resources installed in the install namespace (rather than the target namespace), these resources being; a triggertemplate called `<pipeline-name>-template` and two triggerbindings `<pipeline-name>-push-binding` and `<pipeline-name>-pullrequest-binding`.

**Comment by anneqm** [comment]
@jantley-ibm and I met today, and also discussed including a point in the What's New doc to mention that previously established webhooks will need to be deleted and re-created with this upgrade.  Hotlink to the deleting a webhook instruction: https://kabanero.io/docs/ref/general/configuration/tekton-webhooks.html#deleting-a-webhook

**Comment by jantley-ibm** [comment]
pr merged, closing
