### ISSUE TITLE
Update /docs and guides for 0.5.0 version change

### ISSUE THREAD

**Issue by jantley-ibm** [kabanero-io/docs#258]
Make sure /docs section mentions most recent version where appropriate (partial list in https://github.com/kabanero-io/docs/issues/212).

Make sure any Guides that can be updated are moved to the most recent version too.

**Comment by SueChaplain** [comment]
Guides:

Collections guides:

- [ ] Nodejs-express https://github.com/kabanero-io/guide-collection-nodejs-express/pull/13
- [ ] Nodejs https://github.com/kabanero-io/guide-collection-nodejs/pull/4
- [ ] Nodejs-loopback https://github.com/kabanero-io/guide-collection-nodejs-loopback/pull/4
- [ ] java microprofile https://github.com/kabanero-io/guide-collection-microprofile/pull/25
- [ ] Springboot https://github.com/kabanero-io/guide-collection-springboot2/pull/8

- [x] Working with collections - no update necessary
- [x] Developing with Eclipse IDE (microprofile) - no update necessary
- [x] Using the Appsody CLI - no update necessary

**Comment by alohr51** [comment]
@SueChaplain we'll have to be careful updating the guides. I'm sure they were tested with tools at specific versions. If we just update the versions without retesting the guides, we could put out guides that are broken, which could lead to frustration by readers.

Whether we want to update the guides once every 2 months or every release they should probably be retested with the new version, which can be tedious. 

Another idea is we can ask owners of the guides to do the update, and if they don't have time and the guide becomes really, really outdated, then we can just remove it.

**Comment by SueChaplain** [comment]
@alohr51 - agreed. The ones I targeted are collections. App logging/monitoring and some of the others are tested on specific versions. Jeff and I discussed and these are left alone.

**Comment by jantley-ibm** [comment]
closing
