### ISSUE TITLE
Document configuration of CodeReady workspaces

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/docs#264]
The kabanero-operator can configure codeready workspaces.  We need to document any buttons or switches that affect that configuration.

**Comment by kaczyns** [comment]
Epic is kabanero-io/roadmap#127

**Comment by kaczyns** [comment]
The manual Kabanero install instructions should also be modified to remove the part about installing the Che operator, and replaced with installing the Codeready Workspaces operator.

**Comment by kaczyns** [comment]
hi @mingcyu - I don't feel I'm the right person to be driving this issue from the development side.  I don't understand how to use or configure Codeready Workspaces (or Che).  The operator provides some buttons and switches, which we can call out in the doc, but as far as what they do, someone from the Codewind team may need to help.

**Comment by mezarin** [comment]
I had a chat with @johnmcollier about the documentation for this. He or someone else will be providing the documentation. 
See the description section of this PR https://github.com/kabanero-io/kabanero-operator/pull/444 for kabanero installation details and notes.

**Comment by johnmcollier** [comment]
I can help this, if someone can assign this to me. 

Where in github.com/kabanero-io/docs do the doc changes for this need to go?

**Comment by alohr51** [comment]
@johnmcollier If this is new doc then you can create a new file under [ref/general/configuration](https://github.com/kabanero-io/docs/tree/master/ref/general/configuration) since this sounds like a configuration type of doc.

Also some guidelines are listed in the [docs readme](https://github.com/kabanero-io/docs#how-to-contribute-to-the-documentation)

**Comment by johnmcollier** [comment]
Seems like PR https://github.com/kabanero-io/docs/pull/282, will address the configurable fields for CRW

**Comment by kaczyns** [comment]
I want to be sure that there is some other documentation besides what is being done in #282.  I don't think #282 is enough for someone to be comfortable getting started working with CRW in Kabanero.

**Comment by johnmcollier** [comment]
@kaczyns Ah okay, I thought this doc was just for the configurable fields for CodeReady in the Kabanero CR. 

What were you thinking in terms of docs? Ideally we'd avoid duplication with the existing CodeReady and Codewind docs where possible, right? So do we just need docs for the Kabanero specific areas?

**Comment by kaczyns** [comment]
I think that we need to guide someone in how to set up a CodeReady Workspaces workspace.  I know that if it were me, it would not be clear what to do.

For example this page:
https://kabanero.io/docs/ref/general/installation/installing-dev-tools.html

walks someone thru how to set up codewind in VS code or Eclipse.  None of this is Kabanero-specific yet we guide someone thru how to do it.  Even if it's just links to where the existing documentation is.  Or "go to this website and follow the instructions".

If I'm a user, how would I know whether I want to set any of those options in the Kabanero CR instance?  Do I have to do anything to integrate Codewind into CodeReady Workspaces?  How do I log in?  These are questions I would have.

**Comment by johnmcollier** [comment]
@kaczyns Sounds good, I can get to work on that

**Comment by chirp1** [comment]
Discussed with Jeff @jantley-ibm . Since the doc is relates to the Codeteam, I'm reassigning the issue to Jake.

**Comment by j-c-berger** [comment]
@chirp1, sounds good, thanks!

**Comment by johnmcollier** [comment]
PR up at https://github.com/kabanero-io/docs/pull/296

**Comment by jantley-ibm** [comment]
PR merged, closing as completed
