### ISSUE TITLE
Update documentation terminology 

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/docs#266]
we need to update our terminology in the docs according to the collections -> stacks design from https://github.com/kabanero-io/kabanero-foundation/blob/master/design/stackhub.md

While we're at it, terminology changes from Nate:
Appsody stacks --> application stacks
Tekton pipelines --> pipelines
Tekton Dashboard --> pipelines dashboard
Kabanero stacks --> application stacks
Kabanero pipelines --> pipelines
Kabanero collections --> stack hub or application stack hub
Kabanero operator --> product operator
Appsody operator --> application operator
Kabanero Enterprise --> Accelerator for Teams
Kabanero Custom Resource (CR) --> stays as is

Avoid references to OKD vs. OCP --> Kubernetes deployment
Remove version-specific information --> use &lt;version&gt; instead (precludes having to change them manually every release)

- [x] https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html
    Writer assigned: Jeff Antley
    PR link: https://github.com/kabanero-io/docs/pull/273

- [x] https://kabanero.io/docs/ref/general/installation/installing-dev-tools.html
    Writer assigned: Jeff Antley
    PR link: https://github.com/kabanero-io/docs/pull/273

- [x] https://kabanero.io/docs/ref/general/installation/uninstalling-kabanero-foundation.html
    Writer assigned: Jeff Antley
    PR link: https://github.com/kabanero-io/docs/pull/273

- [x] https://kabanero.io/docs/ref/general/configuration/kabanero-cr-config.html
    Writer assigned: Tim Kaczynski, ID will review
    Issue link: https://github.com/kabanero-io/docs/issues/272

- [x] https://kabanero.io/docs/ref/general/configuration/collection-install.html
    Writer assigned: Tim Kaczynski, ID will review
    PR link: #283

- [x] https://kabanero.io/docs/ref/general/configuration/github-authorization.html
    Writer assigned: Jeff Antley
    PR link: https://github.com/kabanero-io/docs/pull/281

- [x] https://kabanero.io/docs/ref/general/configuration/app-deploy-namespace.html
    Writer assigned: Jeff Antley
    PR link: https://github.com/kabanero-io/docs/pull/281

- [x] https://kabanero.io/docs/ref/general/configuration/console-oauth.html
    Writer assigned: Jeff Antley
    Issue link: https://github.com/kabanero-io/docs/pull/281

- [x] https://kabanero.io/docs/ref/general/configuration/tekton-webhooks.html
    Writer assigned: Jeff Antley
    Issue link: https://github.com/kabanero-io/docs/pull/281

- [x] https://kabanero.io/docs/ref/general/reference/kabanero-cli.html
    Writer assigned: Jeff Antley
    PR link: https://github.com/kabanero-io/docs/pull/280

- [x] https://kabanero.io/docs/ref/general/reference/kabanero-env-vars.html
    Writer assigned: Sue Chaplain
    Issue link: https://github.com/kabanero-io/docs/issues/274
       ~~(this page describes how collection hubs are built -- this will now defer to stack hubs are built. We should look to point at the Appsody process where possible.)~~
    PR link to remove topic: https://github.com/kabanero-io/docs/pull/295

- [x] https://kabanero.io/docs/ref/general/overview/architecture-overview.html
     Writer assigned: Jeff Antley
     PR link: https://github.com/kabanero-io/docs/pull/275

Additionally address version specific references to make more generic
See https://app.zenhub.com/workspaces/planning-5d27848477f50538a6b24121/issues/kabanero-io/docs/212

**Comment by marikaj123** [comment]
The work is on track to complete this week.

**Comment by jantley-ibm** [comment]
all kabanero docs have been updated, reviewed, approved and merged.  closing
