### ISSUE TITLE
Update guides terminology

### ISSUE THREAD

**Issue by alohr51** [kabanero-io/docs#267]
we need to update our terminology in the guides according to the collections -> stacks design in https://github.com/kabanero-io/kabanero-foundation/blob/master/design/stackhub.md#kabanero-guides.

While we're at it, terminology changes from Nate:
Appsody stacks --> application stacks
Tekton pipelines --> pipelines
Kabanero stacks --> application stacks
Kabanero pipelines --> pipelines
Kabanero collections --> stack hub or application stack hub
Kabanero operator --> product operator
Appsody operator --> application operator
Kabanero Enterprise --> Accelerator for Teams
Kabanero Custom Resource (CR) --> stays as is

Avoid references to OKD vs. OCP --> Kubernetes deployment !! KAB ONLY? OR ICPA ALSO?
Remove version-specific information in code samples --> use &lt;version&gt; (in italics) instead (precludes having to change them manually every release)

Finally, convert Asciidoc guides to Markdown.

- [x] https://kabanero.io/guides/use-appsody-cli 
      (remove changes for Appsody CLI -- it is fine for the Appsody CLI to point at the default Appsody link)
      writer assigned: Sue Chaplain
      guide issue link: https://github.com/kabanero-io/guide-use-appsody-cli/issues/9
      PR link: https://github.com/kabanero-io/guide-use-appsody-cli/pull/10
      Converted to markdown? Yes

The section called "Collections" needs to change. The following guides need to change to reflect using these "Stacks" with Kabanero.

- [x] https://kabanero.io/guides/collection-nodejs
      writer assigned: Dave Hobbs
      guide issue and PR link: https://github.com/kabanero-io/guide-collection-nodejs/issues/5
      Converted to markdown? Yes
      Category changed from "collections" to "stacks"? Yes
- [x] https://kabanero.io/guides/collection-nodejs-loopback/
      writer assigned: Dave Hobbs
      guide issue and PR link: https://github.com/kabanero-io/guide-collection-nodejs-loopback/issues/5
      Converted to markdown? Yes
      Category changed from "collections" to "stacks"? Yes
- [x] https://kabanero.io/guides/collection-nodejs-express/
      writer assigned: Sue Chaplain
      guide issue link: https://github.com/kabanero-io/guide-collection-nodejs-express/issues/15
      PR: https://github.com/kabanero-io/guide-collection-nodejs-express/pull/14
      Converted to markdown? Yes
      Category changed from "collections" to "stacks"? Yes
- [x] https://kabanero.io/guides/guide-codewind
      writer assigned: Jacob Berger
      guide issue link: https://github.com/kabanero-io/roadmap/issues/130
      PR Link: https://github.com/kabanero-io/guide-codewind-getting-started/pull/7
      Converted to markdown? Yes
      Category changed from "collections" to "stacks"? Yes
- [x] https://kabanero.io/guides/microprofile-eclipse-codewind **SUPERSEDED BY GUIDE-CODEWIND, ARCHIVE**
      writer assigned: Sue Chaplain
      guide issue link: https://github.com/kabanero-io/guide-microprofile-eclipse-codewind/issues/7
      PR: https://github.com/kabanero-io/guide-microprofile-eclipse-codewind/pull/6
- [x] https://kabanero.io/guides/collection-microprofile
      writer assigned: Dave Hobbs
      guide issue and PR link: https://github.com/kabanero-io/guide-collection-microprofile/issues/26
      Converted to markdown? Yes
      Category changed from "collections" to "stacks"? Yes
- [x] https://kabanero.io/guides/collection-springboot2/
      writer assigned: Dave Hobbs
      guide issue and PR link: https://github.com/kabanero-io/guide-collection-springboot2/issues/9
      Converted to markdown? Yes
      Category changed from "collections" to "stacks"? Yes
- [x] https://kabanero.io/guides/jenkins-integration-with-kabanero/
      writer assigned: Karen Deen
      guide issue link: https://github.com/kabanero-io/docs/issues/277
      Converted to markdown? no; will be tracked in new issue
      Category changed from "collections" to "pipelines"? yes
- [x] https://kabanero.io/guides/working-with-collections/ **ARCHIVE & CREATE NEW GUIDE "Working with Application stacks"**
      writer assigned: Sue Chaplain
      old guide issue link: https://github.com/kabanero-io/guide-working-with-collections/issues/19
      PR: https://github.com/kabanero-io/guide-working-with-collections/pull/20
      Converted to markdown? No - to be archived.
       (this guide will likely need re-enginnering, since the focus is on working with collections, when we want to show the same scenario, but with the simplified focus on stack hubs.)
      new guide PR: https://github.com/kabanero-io/draft-guide-working-with-stacks/pull/1
      Created in markdown
      Category is "stacks"? Yes

- [x] https://kabanero.io/guides/nexus-repository-integration-with-appsody/ 
      writer assigned: Pam Helyar
      guide issue link: https://github.com/kabanero-io/guide-nexus-repository-integration/issues/5
      PR link: https://github.com/kabanero-io/guide-nexus-repository-integration/pull/6
      Converted to markdown? Yes (https://github.com/kabanero-io/guide-nexus-repository-integration/pull/8)
- [x] https://kabanero.io/guides/app-monitoring/
      writer assigned: Pam Helyar (No terminology updates needed. Needs conversion to Markdown.)
      guide issue link: N/A
      Converted to markdown? DO NOT CONVERT
- [x] https://kabanero.io/guides/using-kAppNav/
      writer assigned: Tom Koman
      guide issue link: https://github.com/kabanero-io/guide-using-kAppNav/issues/4
      PR link: https://github.com/kabanero-io/guide-using-kAppNav/pull/5
      Converted to markdown? DO NOT CONVERT
- [x] https://kabanero.io/guides/app-logging/
      writer assigned: Tom Koman
      guide issue link: https://github.com/kabanero-io/guide-app-logging-okd-3.11/issues/17
      PR link: https://github.com/kabanero-io/guide-app-logging-okd-3.11/pull/18
      Converted to markdown? DO NOT CONVERT
- [x] https://kabanero.io/guides/app-logging-ocp-4-2/
      writer assigned: Jeff Antley
      guide issue link: https://github.com/kabanero-io/guide-app-logging-ocp4.2/issues/2
      PR link: https://github.com/kabanero-io/guide-app-logging-ocp4.2/pull/3
      Converted to markdown? Yes (https://github.com/kabanero-io/guide-app-logging-ocp4.2/pull/4)
- [x] https://kabanero.io/guides/pipelines-getting-started/
      writer assigned: Jeff Antley
      guide issue link: https://github.com/kabanero-io/guide-working-with-pipelines/issues/18
      PR link: https://github.com/kabanero-io/guide-working-with-pipelines/pull/17
      PR link: https://github.com/kabanero-io/guide-working-with-pipelines/pull/21
      Converted to markdown? In progress (https://github.com/kabanero-io/guide-working-with-pipelines/pull/22)

- [x] https://kabanero.io/guides/app-monitoring-ocp4.2/
       writer assigned: (No terminology updates needed. Needs conversion to Markdown.)
       PR link: N/A
       Converted to markdown? No; will be tracked in new issue.

Additionally, update version information to make more generic
Refer to this link: https://app.zenhub.com/workspaces/planning-5d27848477f50538a6b24121/issues/kabanero-io/docs/212

**Comment by SueChaplain** [comment]
There's been some recent discussion over when to use  **stack hub** when updating the guides. For the developers guides (developing microservices based on the xx application stack), we are referring only to "stack configuration", because all "Jane" really needs to know is that she adds a URL that contains an `index.yaml` config file to her local dev environment. This avoids any confusion if Champ chooses to implement a 1:1 or 1:many type of configuration.

So this sort of statement: 

*Developers access these stacks by configuring their development environment to point to a stack configuration.*

As opposed to: 

*Developers access these stacks by configuring their development environment to point to a stack hub.*

If anyone sees any issues here, please shout.
@stephenkinder @nateziemann @bschrammIBM

**Comment by SueChaplain** [comment]
FYI - and an opportunity to speak up if you don't agree. 

We (Jeff, Andrew, and I) have been discussing what to do with the main guides that cover collections when collections are removed. Update / archive / delete? What considerations should we have for customers on older versions of Kabanero. 

Long story short:

"Keeping around old guides will confuse people getting started with kabanero (since they will probably be using the latest at that time)"

Archive=Working with Collections, "Developing apps with the Eclipse IDE". These can still be viewed in GitHub, but will not display on the website.
Update=All 5 collections guides, plus "Getting Started with Codewind and Kabanero"

**Comment by stephenkinder** [comment]
So one quirk is that Appsody takes `index.yaml` as its "stack hub" pointer, however Codewind takes `index.json`.

**Comment by SueChaplain** [comment]
>So one quirk is that Appsody takes index.yaml as its "stack hub" pointer, however Codewind takes index.json.

We are not proposing to remove the "Working with Codewind" guide that covers the developer experience with both the Eclipse IDE and VS Code, so users will be able to learn how to configure their environment to point to an `index.json` file. @j-c-berger is assigned to update this guide for the terminology changes.

**Comment by j-c-berger** [comment]
@stephenkinder & @SueChaplain, I did a `contrl+F` on my guide, and there's neither mention of `index.yaml` nor `index.json` 

If there _needs_ to be inclusion of `index.json`, then I certainly can include it, but as of now, there is no terminology issue since neither terminologies are used.

**Comment by SueChaplain** [comment]
> I did a contrl+F on my guide, and there's neither mention of index.yaml nor index.json

Hi @j-c-berger - I hadn't appreciated that your guide does not explain how to add customized stacks (earlier "collections") into the Codewind configuration. We were going to archive this guide, which does provide this explanation here: https://kabanero.io/guides/microprofile-eclipse-codewind/#configuring-your-environment-to-use-a-kabanero-collection-hub

If Champ has customized a stack or set of stacks for Jane to use, she has to add this to her codewind configuration. It comes in the form of a URL to an `index.json` file. 

Perhaps we should consider updating your guide with this information or retaining the one we were going to archive. @stephenkinder ? Thoughts?

**Comment by j-c-berger** [comment]
@SueChaplain,  the guide you linked to (Developing with Kabanero Collections), you only want to include the section, `configuring your environment to use a Kabanero collection hub` into my guide, correct? Two thoughts I have:
1. is it necessary?
2. where to put it in the guide's organization? 

I ask if it's necessary, because right now, the guide's objective is to develop a simple microservice with Codewind in the chosen IDE. Users can accomplish this objective without an `index.json` file. 

If we do want to archive the `Developing with Kabanero Collections`,  and we do want to incorporate the `configuring your environment to use a Kabanero collection hub` into my Codewind  guide, I can do so. But it's going to take me some time to smoothly integrate it into the guide and and convert it to MD.

**Comment by SueChaplain** [comment]
@j-c-berger - don't worry, we'll get the other guide updated for this release and discuss whether there could be any changes to your guide in the future. I think it is necessary to explain to a user how they use Codewind "in the context of Kabanero". Not discussing the `index.json` file anywhere would, I think, be an omission.

**Comment by j-c-berger** [comment]
Okay, so it's the green light to include the `index.json` instructions. But, we'll save that update for a later release, so not for 0.6.0? Thanks!

**Comment by SueChaplain** [comment]
>don't worry, we'll get the other guide updated for this release and discuss whether there could be any changes to your guide in the future.

I took a look at the other guide and the changes are too extensive. There are a lot of screenshots that will need recapturing and at the moment I cannot get Codewind working in my Eclipse IDE. Instead I have reviewed https://github.com/kabanero-io/guide-codewind-getting-started/pull/7 and suggested how the updates could be applied for the additional content about index.json for release 0.6.0.  @j-c-berger please contact me if you need any help.

**Comment by j-c-berger** [comment]
@SueChaplain, thank you for getting back to me and for doing a review of the guide. I made my first read through of your comments and they look on-point! I'll for sure reach out if I have questions. 

I have an all day event this afternoon (my time), but I shall start to apply your feedback this morning and ought to have the guide done tomorrow afternoon (U.S time), so it might not be completed by end of Wednesday (U.K time). 

Thank you for all the help you've been :)

**Comment by marikaj123** [comment]
According to the id team, the work is on track to compete by this week.

**Comment by jantley-ibm** [comment]
closing as completed.
