### ISSUE TITLE
Remove Knative eventing and service mesh from the manual install instructions

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/docs#271]
For Kabanero 0.6.0, Knative Eventing is no longer required.  Service Mesh also no longer needs to be manually configured.  They are both referenced here in the manual install steps:
https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html

**Comment by marikaj123** [comment]
@kaczyns - would the work be done by your team?  Do we need Id involvement?

**Comment by jantley-ibm** [comment]
@marikaj123 @kaczyns I am in the process of trying to make edits to this doc for branding and terminology, so I don't mind making the edit.  Is it a simple matter of just removing step 2 and the second sentence of step 1?

**Comment by kaczyns** [comment]
@jantley-ibm Yes that's correct - we remove the install of knative-eventing, and remove the reference of service-mesh from the serverless install instructions.

**Comment by jantley-ibm** [comment]
fixed in #286

**Comment by jantley-ibm** [comment]
closing as fixed
