### ISSUE TITLE
Removing collections: Address Environment Variables topic

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#274]
The current topic describes the environment variables that can be used when you are building Kabanero Collections. In the new design, Champ will use Appsody directly to customise and build Stacks.

Propose we remove this topic altogether as I am not aware of any other environment variables that are required, other than for building collections.

We are proposing a new guide for how Champ clones / updates / builds application stacks for his org. If there are env vars required, we will mention them here.

**Comment by SueChaplain** [comment]
@mtamboli @gecock - are you aware of any other Kabanero components that have environment variables we should document? If not, I'm proposing to remove this topic, which contains the envvars for collection build. Thanks

**Comment by mtamboli** [comment]
@SueChaplain I am probably missing some context for this. Are you talking about removing environment variable from a guide or script?

**Comment by SueChaplain** [comment]
Sorry @mtamboli - I'm talking about this topic: https://kabanero.io/docs/ref/general/reference/kabanero-env-vars.html

**Comment by mtamboli** [comment]
Thanks @SueChaplain I am sure this will need to be updated but I have not see the new scripts so not sure which ones will stay. @groeges probably would be able to help on what need to be updated. It would nice to get draft of those documents during testing.

**Comment by SueChaplain** [comment]
@groeges - please can you confirm if there is any reason to keep any of the existing content. I thought it was all going?

**Comment by SueChaplain** [comment]
Received confirmation from Steve G that this topic is no longer required for 0.6.0. As we are not aware of any other environment variables that are used in other components, this topic will be removed.
