### ISSUE TITLE
terminology updates for guide-jenkins-integration-with-kabanero

### ISSUE THREAD

**Issue by chirp1** [kabanero-io/docs#277]

**Comment by chirp1** [comment]
Slack from 2/6/20: From Steve Kinder, guide actually doesn’t work, Brian Sullivan  Brian Sullivan attempting to work on guide.

 Checked with Checked with Jeff who indicated to let it be until it is revised.

**Comment by marikaj123** [comment]
According to the id team, @brianxjx  is making technical changes and is expecting to be done this week.

**Comment by jantley-ibm** [comment]
closing as completed
PR: https://github.com/kabanero-io/guide-jenkins-integration-with-kabanero/pull/23
