### ISSUE TITLE
Doc changes in kabanero.io for Kabanero CLI 0.6.0

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#285]
Need Doc changes in kabanero.io for Kabanero CLI 0.6.0, especially around examples now that we have converted to stack hubs and multiple version support

Updates need to make it into:
https://kabanero.io/docs/ref/general/reference/kabanero-cli.html

**Comment by davco01a** [comment]
new example output:

```

Kabanero CLI service url:  kabanero-cli-kabanero.apps.happening.os.fyre.ibm.com

Kabanero Instance Stacks 	Version	Status
-------------------------	-------	------
java-microprofile		0.2.21	active
java-spring-boot2		0.3.21	active
nodejs				0.3.1	active
nodejs-express			0.2.8	active
nodejs-loopback			0.1.8	active

GitHub Curated Stacks (repo name - url):
   central - https://raw.githubusercontent.com/kabanero-io/kabanero-command-line-services/master/index.yaml

GitHub Curated Stacks	Version	Repo
---------------------	-------	----
java-microprofile	0.2.21	central
java-spring-boot2	0.3.21	central
nodejs			0.3.1	central
nodejs-express		0.2.8	central
nodejs-loopback		0.1.8	central
```

**Comment by davco01a** [comment]
sync output:

```
claudias-mbp kabanero-command-line =>./build/kabanero sync
Kabanero Instance Stacks 	Version	Status
-------------------------	-------	------
java-microprofile		0.2.21	added to Kabanero
```

**Comment by davco01a** [comment]
LIST output with obsolete stack:

```

Kabanero CLI service url:  kabanero-cli-kabanero.apps.happening.os.fyre.ibm.com
Kabanero Instance Stacks    Version Status
-------------------------   ------- ------
java-microprofile       0.2.21  active
java-spring-boot2       0.3.21  active
nodejs              0.3.1   active
nodejs-express          0.2.8   active
nodejs-loopback         0.1.8   active
java-microprofile       0.2.21  obsolete

**Comment by davco01a** [comment]
SYNC operation deleting obsolete stack:

```
claudias-mbp kabanero-command-line =>./build/kabanero sync
Kabanero Instance Stacks    Version Status
-------------------------   ------- ------
java-microprofile       0.2.21  deleted

**Comment by jantley-ibm** [comment]
@davco01a I'm having trouble reconciling the latter two examples you provided with the cli doc.  Is the 'obsolete' state a replacement for the 'deactivated' state?  There is currently no discussion of a delete command, could you provide an example command and some explanatory verbage?

**Comment by davco01a** [comment]
Sure we can add some explanation:

obsolete state is when a given Stack is no longer in the GitHub Curated Stacks list, but it still exists as a Kabanero Instance

When a stack is obsolete and a SYNC is performed that obsolete version of the stack will get deleted

**Comment by davco01a** [comment]
kabanero deactivate stack-name version-number

**Comment by davco01a** [comment]
e.g.

```
± |nocoll → origin U:4 ?:4 ✗| → build/kabanero deactivate nodejs 0.3.1
Stack name: nodejs version: 0.3.1 deactivated

**Comment by davco01a** [comment]
Also updated LIST w obsolete example above ( multiple versions too )

**Comment by jantley-ibm** [comment]
@davco01a thanks for the explanation and updates.  How does a stack become 'obsolete' ?

**Comment by davco01a** [comment]
A stack becomes Obsolete if the `solution architect` removes a stack from the curated collection on Git hub

It's obsolete because it's still a stack in Kabanero, but no longer in the curated collection.  A SYNC will delete the obsolete stack from Kabanero.

**Comment by jantley-ibm** [comment]
These changes are included in https://github.com/kabanero-io/docs/pull/280

**Comment by jantley-ibm** [comment]
#280 is merged, closing
