### ISSUE TITLE
document known issue: Pre 0.5 releases incompatible with Appsody CLI 0.55 / 0.66

### ISSUE THREAD

**Issue by jantley-ibm** [kabanero-io/docs#289]
See https://github.com/kabanero-io/kabanero-foundation/issues/156

**Comment by jantley-ibm** [comment]
@kaczyns @kilnerm @kvijai82 Could you clarify which Kabanero releases this should this be doc'd in?  It seems to make most sense to put the update in the documentation in the releases prior to 0.5.

**Comment by kaczyns** [comment]
@jantley-ibm I think that was the intention, so Kabanero 0.1.x, 0.2.x, 0.3.x and 0.4.x.

**Comment by jantley-ibm** [comment]
PRs #301 , #312, #314 merged, closing
