### ISSUE TITLE
Guide for developing microservice apps with the OpenLiberty application stack

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#307]
This requires a new guide so that we have a complete set across the stacks.

**Comment by SueChaplain** [comment]
@scottkurz - if we can use the same example code as we have for [Eclipse MicroProfile](https://kabanero.io/guides/collection-microprofile/) this probably requires no input from you. If it doesn't, or you'd like to provide a different example, please let us know.

**Comment by scottkurz** [comment]
@awisniew90

**Comment by awisniew90** [comment]
I don't see a problem with using the same example. The Open Liberty stack should function same way. One thing to note is that the file structure will be a bit different with a few more classes and config files. Nothing within the guide should have to change though.

**Comment by davehobbs** [comment]
@awisniew90 Can you take a quick look at PR kabanero-io/draft-guide-collection-java-openliberty#1 for the Open Liberty guide. It is basically the same as the Microprofile guide with some small changes.

**Comment by awisniew90** [comment]
@davehobbs  - done!

**Comment by SueChaplain** [comment]
@alohr51 - this guide is now ready to publish.

**Comment by mingcyu** [comment]
Completed
