### ISSUE TITLE
Document the workaround for https://github.com/openshift/console/issues/4444

### ISSUE THREAD

**Issue by tam512** [kabanero-io/docs#309]
For Kabanero 0.6.0 in OCP 4.3, users need to use command line (_`oc edit kabanero -n kabanero -o yaml`_) to update the the Kabanero CR instance. The OCP 4.3 GUI is still using the older `apiVersion: kabanero.io/v1alpha1` , so any update to Kabanero CR instance using **GUI** will be saved in the older format of collections and Che instead of stacks and codeReadyWorkspace

**Comment by marikaj123** [comment]
@jantley-ibm - Can the issue be closed?

**Comment by jantley-ibm** [comment]
Yes, issue is mentioned in both troubleshooting and kabanero-cr-config.html, closing
