### ISSUE TITLE
Document the limitation of unable to launch Tekton Dashboard from Codewind in CodeReadyWorkspaces

### ISSUE THREAD

**Issue by tam512** [kabanero-io/docs#316]
Tekton dashboard can't be launched from Codewind in CodeReadyWorkspaces.  Please see defect https://github.com/kabanero-io/kabanero-operator/issues/536 for more detail.  The fix will be in the later release of Kabanero

**Comment by mingcyu** [comment]
@j-c-berger Can you take a look at this one as it relates to Codewind?

**Comment by j-c-berger** [comment]
The Codewind ID team will investigate at our next scrum, so I'll have an update at our upcoming Kabanero Docs planning meeting.

**Comment by j-c-berger** [comment]
No work for Codewind to do, thanks!
