### ISSUE TITLE
Need more specifics on what OKD Install Steps to follow

### ISSUE THREAD

**Issue by erpenbach** [kabanero-io/docs#32]
On the page:
https://kabanero.io/operations/kabanero-foundation-setup/ 
There is a link to OKD Install Instructions which takes you to https://docs.okd.io/latest/getting_started/administrators.html.

More specifics on what part of instructions are needed or not needed would be helpful.

**Comment by alohr51** [comment]
The [latest install doc](https://github.com/kabanero-io/docs/blob/master/ref/general/installing-kabanero-foundation.adoc) doesn't have the link to https://docs.okd.io/latest/getting_started/administrators.html anymore.
