### ISSUE TITLE
Guide on how to curate pipelines 

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/docs#333]
Will provide content here shortly.

**Comment by kvijai82** [comment]
@jantley-ibm Have a draft written up here: https://github.com/kabanero-io/kabanero-pipelines/blob/doc-curate/docs/Curation.md

Please review and let me know if you need more info.  Thanks!

**Comment by jantley-ibm** [comment]
@chirp1 could you review this new guide, keeping an eye to the terminology guidance in #267 ?

**Comment by jantley-ibm** [comment]
@t-koman could you review this guide?

**Comment by t-koman** [comment]
@jantley-ibm Yes I can review it......   Ming also assigned me  https://github.ibm.com/IBMCloudPak4Apps/icpa-docs-kc/issues/327

**Comment by t-koman** [comment]
@jantley-ibm Jeff, is the process to create a branch, make edits, then share those edits with the author, who will perform the pull request?   I do not want to integrate any of my suggested changes unless the author agrees......  Is this right way to process the reviews ?   thanks

**Comment by jantley-ibm** [comment]
@t-koman create a branch, make your changes, commit, push, create a PR, assign the author as a reviewer of the PR.  Author reviews, you can make edits and push to the same PR, author approves and merges when all done.

**Comment by t-koman** [comment]
@jantley-ibm Thanks for the instrutions.... it looks like after I create the PR, assign the author as reviewer of the PR....We can go back and forth with the PR..... until the author approves it, then the author does the merge .... correct ?

**Comment by bschrammIBM** [comment]
@kvijai82 @t-koman Please confirm that all pipeline instructions are correct for the procedure for creating the PV. We previously documented it as optional, is this still correct?

**Comment by bschrammIBM** [comment]
epic is https://github.com/kabanero-io/kabanero-pipelines/issues/178

**Comment by jantley-ibm** [comment]
completed, closing
