### ISSUE TITLE
Review and update Codewind documentation for MVP release

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#34]
https://www.eclipse.org/codewind/docindex.html

The Codewind documentation requires review and updating.
Need to ensure:
1) Is it accurate for both Kabanero and Cloud Pak for Apps.
2) Tag any content that applies only to Kabanero or only to CP4Apps.
3) Provide content for additional Guides for Codewind - perhaps we could include a Guide for "Using Codewind with Kabanero" and "Using Codewind with IBM Cloud Pak for Apps"?

**Comment by bschrammIBM** [comment]
@bsbyrd assigned

**Comment by jantley-ibm** [comment]
Jake Berger (ID)

**Comment by j-c-berger** [comment]
Am currently working on a guide for Codewind. I'll ensure the guide meets these needs.

**Comment by j-c-berger** [comment]
Finished in repo, not yet published to Kabanero.io.
