### ISSUE TITLE
Write a Guide for "Using the Eclipse MicroProfile Collection"

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#36]
We need a Guide for how to work with the pre-packaged Eclipse MicroProfile collection. Eclipse MicroProfile is included in the MVP release. Here is a very rough outline for how to document the pre-packaged collections:

- "A Kabanero Collection provides guides for developers, templates for simplicity and consistency of developing applications, a runtime in a certified base container image infused with expertise for Kubernetes deployments, and an integrated toolchain for developing with modern tools. Eclipse MicroProfile is a set of APIs used to optimize Java applications for a microservices architecture. With this stack, you can deliver microservices based upon the Eclipse MicroProfile specifications. Build and run high-quality applications with Open Liberty runtime, which includes OpenJDK with container-optimizations in OpenJ9."  (taken from the Kabanero.io website)  

- Add more information for how Collections are used, what the prerequisites are for the Collection, how it can be customized, etc.

- Components in the Eclipse MP Collection - Describe the functionality of the components. [OpenLiberty, Operators, Prometheus (Grafana?), Tekton]
- How to use a Collection for coding standards and pipelines (Champ)
- How to use a Collection for development (Jane)
- How to set up serverless
- Ideas for how to document collections?

**Comment by bschrammIBM** [comment]
From @nateziemann Collection Guides should look and flow like one of the Open Liberty Guides.
For example, https://openliberty.io/guides/getting-started.html

**Comment by bschrammIBM** [comment]
@lloyd roseblade

**Comment by bschrammIBM** [comment]
There may be some information for the Eclipse Microprofile Guide here:
https://github.com/gcharters/kabanero-dev-getting-started

This is an internal github repo, so contact Graham Charters to confirm its accuracy.

**Comment by bschrammIBM** [comment]
From release planning meeting:

```
from David Harris to Everyone: 
from chatting to Ian, the collections are published but its the deploy that we need working so we can demo and doc
```

**Comment by bschrammIBM** [comment]
@ianpartridge can provide the information for this Guide. We'd like to have it completed by 8/28.

**Comment by bschrammIBM** [comment]
There may be some information for the Eclipse Microprofile Guide here:
https://github.com/gcharters/kabanero-dev-getting-started
This is a personal github repo, so contact Graham Charters to confirm its accuracy. Graham has replied "The link you included is where I'll be developing the Kabanero workshop that will use MicroProfile on Open Liberty. I haven't started on the collections piece because collections seem to be up-in-the-air at the moment and I'd like to avoid too much rework. The workshop is intended to be in two parts (developer creating a new microservice, and architect creating or modifying a stack)."

**Comment by Charlotte-Holt** [comment]
@bschrammIBM @dianak2016 Can you confirm the date that this guide needs to be ready to publish?

**Comment by bschrammIBM** [comment]
It was originally scheduled for 9/13, dependent upon receiving the info from engineering.

**Comment by Charlotte-Holt** [comment]
Okay, thanks @bschrammIBM. At this point, we're still waiting on the info from engineering.

**Comment by SueChaplain** [comment]
This one is now live: https://kabanero.io/guides/collection-microprofile/

Closing this issue
