### ISSUE TITLE
Broken link when referencing Codewind doc

### ISSUE THREAD

**Issue by j-c-berger** [kabanero-io/docs#362]
On the [Installing Codewind in CodeReady Workspaces](https://kabanero.io/docs/ref/general/installation/installing-codeready-and-codewind.html) under the ```Installing Codewind``` section, there's the link, ```Codewind on Che documentation``` This link ought to link to the page, ```che-installinfo.html``` 

Right now, it currently does not, hence, the broken link.

**Comment by sishida** [comment]
Hi, team, Today I found this 404 page on the Appsody website: https://kabanero.io/guides/guide-codewind/. I got here from an internet search result.

@alohr51 Andrew, Jake suspects that this is the old Codewind guide (before it was split into two). Could you please remove it? Thank you!
