### ISSUE TITLE
Document local installation of Codewind for Kabanero

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#37]
Document how to install Codewind locally.
There are installation instructions in the Codewind docs here:
https://www.eclipse.org/codewind/installlocally.html
There are installation instructions on kabanero.io website here:
https://kabanero.io/developer/ide/
There are new instructions included in the proposed Getting Started flow.
Review and update these instructions to be complete and accurate.

**Comment by jantley-ibm** [comment]
Brandy Byrd (ID)

**Comment by j-c-berger** [comment]
I will go over these instructions while including installation instructions in the Codewind guide.

**Comment by j-c-berger** [comment]
Here are the links to the Markdown files for the IDEs, Eclipse Che, Eclipse, VS Code:

1. Eclipse Che: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/installoncloud.md

2. Eclipse: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-eclipse-installinfo.md

3. VS Code: https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/mdt-vsc-installinfo.md

**Comment by j-c-berger** [comment]
Finished in repo, not yet published to Kabanero.io

**Comment by alohr51** [comment]
@j-c-berger what needs to be published to kabanero.io? You should link a PR to this issue

**Comment by j-c-berger** [comment]
@alohr51, I made this comment per Barbara Schramm's suggestion. We didn't want to close the issue since it has yet to be published. But for now, the work for this issue is completed (it's not currently being worked on). 

My ID team will discuss what to do with this issue and how to close moving forward. 

Thank you for your attention.
