### ISSUE TITLE
Handle mismatching container digests in Console UI

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/docs#371]
### What version of Kabanero does this apply to?
- Latest __

### Specify what you want documented (required):
Complete the following information:

#### To create a topic:
- Specify a link to the section in the navigation where the topic should go:
- Specify a first draft of the topic that you want added:

#### To update existing topics:
- Specify links to the topics that are affected:
- Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:

**Comment by tseelbach** [comment]
blocked by https://github.com/kabanero-io/kabanero-landing/issues/179

**Comment by alohr51** [comment]
@tseelbach what kind of content did you have in mind? Documenting the Console's UI? Or Digest stuff in general?

**Comment by tseelbach** [comment]
@alohr51 the stack-governance.adoc covers most of it.   The page is missing any advice on what to do if there is a mismatch.  That could be a separate - followup work item....
I haven't looked at Landing page.  If you think stack-governamce.adoc covers it, and its linked from Landing, then you can close the issue i think

**Comment by alohr51** [comment]
stack governance is included in the landing docs @tseelbach should we close this out and create a follow up issue for dev/doc to include a doc update to include a what to do scenario?

**Comment by marikaj123** [comment]
@tseelbach - Are we OK to close this issue?

**Comment by marikaj123** [comment]
Tom, Closing this issue as Kabanero 0.9 was completed and no response was provided at the time.
