### ISSUE TITLE
Add doc for TLS verification in pipelines

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/docs#373]
### Add label "documentation-id"
- Add the `documentation-id` bug label to this issue.

### What version of Kabanero does this apply to?
- Latest (0.8.0)

#### To update existing topics:
Will need to update working with pipelines guide.  Will provide content shortly.

**Comment by aadeshpa** [comment]
## TLS verification setup for Image registry used in pipelines

By default all the pipelines are TLS verify enabled and you would need to setup the pipelines connection to the image registries, that the pipelines use for pushing and pulling the container images. Below are the scenarios of image registries that can be used and the setup steps required in each case.

As per this [Image configuration resources](https://docs.openshift.com/container-platform/4.2/openshift_images/image-configuration.html#images-configuration-file_image-configuration) your cluster has a cluster resource `image.config.openshift.io/cluster` where you can configure the image registry settings.

### Enable TLS Verification for your image registry :-

#### Private image registries or :
 
In case of private image registries if you have the certificates that is signed by trusted authorities for your private registry and if you want to encrypt the connection to your private registry you can enable your cluster with those ca signed certificate files. When you run the pipelines these ca certificates will be accessed and your tls verified connection will be set to the private image registry.

Steps to be followed:
 - You should have access to the ca.crt files for your private registries.

 - Follow the instructions from [adding certificate authorities to the cluster](https://docs.openshift.com/container-platform/4.3/builds/setting-up-trusted-ca.html#configmap-adding-ca_setting-up-trusted-ca) and create a configmap with the `key` as your private registry `hostname` and value as the content of your private registry `ca.crt` file. This configmap should be present in the `openshift-config` namespace.

#### Internal openshift image registry external route

- In case of internal openshift image registry that is provided in your OCP(OpenShift containt platform) cluster if you want to secure tls connection to it you can do that for the external route of the internal image registry.

- If you do not have the external route setup for your internal image registry on your cluster you can run below command to enable the default external route

```
oc patch configs.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"defaultRoute":true}}'
```

- Verify you have the external route by below command and check `externalRegistryHostnames`

```
oc get image.config.openshift.io/cluster -o yaml 
```
Sample output
```
# oc get image.config.openshift.io/cluster -o yaml 
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2020-03-24T16:34:58Z"
  generation: 11
  name: cluster
  resourceVersion: "8570660"
  selfLink: /apis/config.openshift.io/v1/images/cluster
  uid: 7ba0dae1-c579-4adf-828d-44b0c3652bae
spec: {}
status:
  externalRegistryHostnames:
  - default-route-openshift-image-registry.apps.incult.os.fyre.ibm.com
  internalRegistryHostname: image-registry.openshift-image-registry.svc:5000
```



### Disable TLS verification setup :- 



#### Internal route url

#### External route url


## Running pipelines

**Comment by t-koman** [comment]
@aadeshpa @kvijai82 Ashish and Vajai - I am picking this issue up as part of the work of the ID team and would like to know what you have in mind for **Adding doc for TLS verification in pipelines** ??   I see that you, Ashish, have added some substantial content in your last post.   How should I proceed so that the work that I will do on this issue will meet your requirements...... thanks

**Comment by kvijai82** [comment]
## TLS verification for image registry access in pipelines

The pipelines leverages the configuration creation of the cluster resource, `image.config.openshift.io/cluster`(https://docs.openshift.com/container-platform/4.2/openshift_images/image-configuration.html#images-configuration-file_image-configuration), when accessing image registries to pull and push images.  of the Below are the scenarios of image registries that can be used and the setup steps required in each case.

### Enable TLS verification for image registry access:

#### Private image registries:
 
If you are using a private image registry and your registry uses certificates that are signed by a well know trusted CA authorities no additional configuration is needed to enable tls verification.   Review the default trust store on the nodes of your cluster to ensure you have the CA of your certificate in the list.  If you are using self signed certificates or have a certificate that's signed by a CA that's not already in the default trust store, follow the steps below to add the CA to the trusted list.  When you run the pipelines these CA certificates will be used.

Steps to be followed:
 - You should have access to the ca.crt files for your private registries.

 - Follow the instructions from [adding certificate authorities to the cluster](https://docs.openshift.com/container-platform/4.3/builds/setting-up-trusted-ca.html#configmap-adding-ca_setting-up-trusted-ca) and create a configmap with the `key` as your private registry `hostname` and value as the content of your private registry `ca.crt` file. This configmap should be present in the `openshift-config` namespace.

#### Internal openshift image registry external route

If you are using the internal openshift image registry that is provided in your OCP(OpenShift container platform) cluster and want to access it using the external route, follow the steps below.

- If you do not have the external route setup for your internal image registry on your cluster you can run below command to enable the default external route

```
oc patch configs.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"defaultRoute":true}}'
```

- Verify you have the external route by below command and check `externalRegistryHostnames`

```
oc get image.config.openshift.io/cluster -o yaml 
```
Sample output
```
# oc get image.config.openshift.io/cluster -o yaml 
apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2020-03-24T16:34:58Z"
  generation: 11
  name: cluster
  resourceVersion: "8570660"
  selfLink: /apis/config.openshift.io/v1/images/cluster
  uid: 7ba0dae1-c579-4adf-828d-44b0c3652bae
spec: {}
status:
  externalRegistryHostnames:
  - default-route-openshift-image-registry.apps.incult.os.fyre.ibm.com
  internalRegistryHostname: image-registry.openshift-image-registry.svc:5000
```

- Once you have the external route, and you should have the ca.crt for the internal image registry external route, follow the same steps as per the steps in section above entitles `Private image registries`.  @aadeshpa how do you get the ca.crt?  can we add a pointer here?

### Disable TLS verification for image registry access:

If your private or internal registry does not have a valid TLS certificate or supports only HTTP connections, you must configure your cluster to allow pulling images from this registry by disabling TLS verification. To accomplish that, run the following command with your registry:

```
oc patch --type=merge --patch='{
 "spec": {
   "registrySources": {
     "insecureRegistries": [
       "<registry>", "abc.com" , "pqr.com"
     ]
   }
 }
}' image.config.openshift.io/cluster

```

If you have multiple image registries, the entries should be a comma separated list as shown above where the image registries url are `abc.com` , `pqr.com`

NOTE: when accessing the internal registry using the internal route, the pipelines will disable tls verification by default.

**Comment by kvijai82** [comment]
@t-koman @jantley-ibm can we add the above to the working with pipelines guide?  A separate request, and I can open a separate issue for this if you agree, can we make this pipelines guide into a pipelines doc?  Would like to start referring to sections of this doc from other smaller guides going forward.

**Comment by jantley-ibm** [comment]
@kvijai82 Yes, to both questions. Create the new issue with a target of v0.9.0. 

@t-koman please add the provided text to the kabanero "working with pipelines" guide in the /guides repo, and also do a regular ID review. Assign both me and Vijai as reviewers on the PR. Needed by end of day Wednesday of this week. Thanks!
