### ISSUE TITLE
New documentation for events-operator

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/docs#385]
### What version of Kabanero does this apply to?
- Specify versions: 0.9.0

### Specify what you want documented (required):
Complete the following information:

#### To create a topic:
- Specify a link to the section in the navigation where the topic should go:
- Specify a first draft of the topic that you want added:

Create a new topic about Kabanero events infrastructure.
Current draft documentation located at:  https://github.com/kabanero-io/events-operator/tree/prototype

**Comment by jantley-ibm** [comment]
guide and reference doc https://github.com/kabanero-io/docs/pull/392 merged, closing
