### ISSUE TITLE
Document TLS cert setup for Kabanero CLI client

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#386]
Document TLS cert setup for Kabanero CLI client

**Comment by s1cyan** [comment]
PR : https://github.com/kabanero-io/kabanero-command-line/pull/232

**Comment by s1cyan** [comment]
To get the Cert run: 
`openssl s_client -connect <kab CLI url>:443 -servername <kab CLI url>` 
Copy and paste the content (from“-----BEGIN CERTIFICATE-----“ and including“-----END CERTIFICATE -----“)

**Comment by s1cyan** [comment]
This is a two part issue:

1. Update docs that login procedure has changed slightly

2. How to get the cert for new login
