### ISSUE TITLE
Need doc on creating Kube secret for accessing container registries for Operator and CLI Service

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#393]
Need doc on creating Kube secret for accessing container registries for Operator and CLI Service

**Comment by davco01a** [comment]
Will need to get this into Kabanero.io or equivalent, CLI service config doc will need to link to this

**Comment by davco01a** [comment]
e.g.

```
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret-token
  annotations:
    kabanero.io/docker-0: https://docker.io
type: kubernetes.io/basic-auth
stringData:
  username: uuuuuu
  password: pppppppppp

**Comment by kaczyns** [comment]
Is this sufficient?
https://github.com/kabanero-io/docs/blob/master/ref/general/configuration/stack-governance.adoc
