### ISSUE TITLE
The guide for working with pipelines has stale information which needs to be removed.

### ISSUE THREAD

**Issue by aadeshpa** [kabanero-io/docs#395]
### Add label "documentation-id"
- Add the `documentation-id` bug label to this issue.

### What version of Kabanero does this apply to?
- Latest __
  or
- Specify versions: _____ kabanero 0.9.0

### Specify what you want documented (required):
Complete the following information:

https://github.com/kabanero-io/guides/blob/master/publish/working-with-pipelines/working-with-pipelines.md

#### To create a topic:
- Specify a link to the section in the navigation where the topic should go:

- Specify a first draft of the topic that you want added:

#### To update existing topics:
- Specify links to the topics that are affected:

The specific location link that needs to be updated:
https://github.com/kabanero-io/guides/blob/master/publish/working-with-pipelines/working-with-pipelines.md#the-build-push-and-deploy-pipeline

- Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:

Existing Text:
```
dockerimage-name-lowercase-task.yaml

This task is needed because Docker requires that a container's imagename be lowercase. This task inputs the docker-imagename and docker-imagetag parameters and builds the docker-image resource URL path with docker-imagename as lowercase letters. In the case when the docker-imagename parameter is empty or not provided, the docker-image URL path is constructed by using the imagename from the existing app-deploy.yaml file. This app-deploy.yaml file should be present in the git-source project that is provided as an input to the pipeline.
```
Update: To remove whole above existing text

**Comment by jantley-ibm** [comment]
PR merged, closing
https://github.com/kabanero-io/guides/pull/56
