### ISSUE TITLE
Document single installation for Kabanero Foundation on Kubernetes

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#40]
Need the installation instructions for this use case. This covers installation for all components running on Kube on local data center or any public cloud.

- Todd installs this by first installing OKD/OCP 
- Then runs the Kab operator

**Comment by stephenkinder** [comment]
At least for these early releases of Kabanero, we have limited our deployment environment to OKD/OCP.  For the Kabanero open project, we specifically describe the installation of Kabanero here: https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts/README.md

**Comment by jantley-ibm** [comment]
@stephenkinder @dacleyra Does that readme satisfy this requirement, or is more needed?

**Comment by dacleyra** [comment]
README needs to be updated with instructions on driving the webhook with tekton dashboard ui. The webhook script is now invalid with tekton behind OKD/OCP oauth.

**Comment by dmuelle** [comment]
Creating/ driving & monitoring webhooks via Tekton documented in https://github.com/kabanero-io/docs/blob/master/ref/general/tekton-webhooks.adoc

**Comment by dmuelle** [comment]
Hi @dacleyra @stephenkinder  @bschrammIBM  

Does the  [Installing Kabanero Foundation](https://kabanero.io/docs/ref/general/installing-kabanero-foundation.html) doc on the Kabanero site satisfy this issue? If not, what is required? 

Thanks!

**Comment by stephenkinder** [comment]
@dmulle I believe that Dan is suggesting that the documentation here: https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/README.md needs some update, if i'm reading the issue correctly.

**Comment by dmuelle** [comment]
@stephenkinder I think you're right, but from what I can tell the readme has been updated since Dan made that comment. The page on the Kanbanero site has some of the same info, but is missing the section on webhook-driven pipline runs (which is covered [elsewhere on the kabanero site](https://kabanero.io/docs/ref/general/tekton-webhooks.html)) and the section on `Uninstalling`, which, as far as I can tell, is not covered on the Kabanero site.

I'm not sure if the updated readme is sufficient to satisfy this issue or if further updates to the Kabanero site are required.

**Comment by dacleyra** [comment]
For webhook, this
https://kabanero.io/docs/ref/general/tekton-webhooks.html

is the same purpose as this section of the scripts README

https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/README.md#sample-appsody-project-with-webhook-driven-tekton-pipeline-run

---

Uninstall script was recently added

https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/README.md#uninstallation-scripts

https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/uninstall-kabanero-foundation.sh

The following issue is open to track that work

https://github.com/kabanero-io/docs/issues/62

---

I don't think there's any additional work to be done in this issue

**Comment by stephenkinder** [comment]
Thanks @dacleyra.  Closing issue.
