### ISSUE TITLE
After Install where do i go next?

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/docs#400]
Release:  0.9.0
Page:
https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html#after-installation

Question: When I get to "after-installation" where do i go?
What design approach is useful for this section?  
Does it make sense to say:  for developers go here, for enterprise architects go here, if you want to verify your install, go here, etc

Right now  the after-install section is a list without too much clear direction.
Having just a pointer to Guides is too broad, may want to have pointers to guides per user role.

After 090 we have a few more possible next steps:
you can choose to configure namespaces/teams/service accounts,   
You need to choose between event, gitops, or existing pipeline approaches.

**Comment by tseelbach** [comment]
After meeting with Design team (Melissa, Jay, Patrick) we decided on the following tactical steps:
https://github.com/kabanero-io/docs/issues/409
https://github.com/kabanero-io/docs/issues/411

**Comment by mingcyu** [comment]
Closing but continuing to track in in 409 and 411
