### ISSUE TITLE
Write an overview guide of Kabanero with diagrams and development process

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#41]
We need a Kabanero overview describing the architecture, components, and workflows. It should include a description of the development process from both Champ's and Jane's POV.

**Comment by bschrammIBM** [comment]
A draft can be created from Powerpoints and other blog entries. Not assigned yet.

**Comment by bschrammIBM** [comment]
https://github.com/nastacio will work on this.

**Comment by jantley-ibm** [comment]
Due Sept. 13

**Comment by nastacio** [comment]
Second draft ready at:
https://github.com/kabanero-io/draft-guide-overview
