### ISSUE TITLE
Write an Appsody CLI guide for developer experience using CLI

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#43]

**Comment by SueChaplain** [comment]
First part, **discover**, is now converted to Asciidoc and added to repo: https://github.com/kabanero-io/draft-guide-use-appsody-cli/

Permalink set to /guides/use-appsody-cli/ and `information-dev` team given maintain access (@alohr51 - hope I did this correctly)

**Comment by marikaj123** [comment]
@SueChaplain  and @alohr51 - Are the content ready for Alan/Nate to review? If yes, please make them as reviewers to the PR.  Thank you.

**Comment by SueChaplain** [comment]
@marikaj123 - pull request https://github.com/kabanero-io/draft-guide-use-appsody-cli/pull/2 ready. Nate and Alan added as reviewers.

**Comment by SueChaplain** [comment]
@alohr51 - please watch the review as I believe your team need to rename the repo for publish. Thanks

**Comment by SueChaplain** [comment]
@alohr51 - this guide is now ready to be published: https://github.com/kabanero-io/draft-guide-use-appsody-cli

Alan approved and I checked that the website team have `admin` for the repo. Thanks!

**Comment by alohr51** [comment]
Guide is published https://kabanero.io/guides/use-appsody-cli/
