### ISSUE TITLE
Tekton sample fails to deploy

### ISSUE THREAD

**Issue by jagraj** [kabanero-io/docs#45]
I tried to install Tekton sample through scripts and it failed to deploy. Here is the message that I get. 

```
Pipeline kabanero/appsody-build-pipeline can't be found:pipeline.tekton.dev "appsody-build-pipeline" not found
```

![Screen Shot 2019-08-13 at 2 35 24 PM](https://user-images.githubusercontent.com/713849/62967752-a1b32000-bdd7-11e9-98c2-ffffdc643ff9.png)

**Comment by mtamboli** [comment]
I am seeing the same issue at http://tekton-dashboard.natives1.fyre.ibm.com/#/namespaces/kabanero/pipelines/appsody-build-pipeline/runs/appsody-manual-pipeline-run

**Comment by alohr51** [comment]
@dacleyra FYI I assume this is about the scripts in https://github.com/kabanero-io/docs/tree/master/ref/scripts

**Comment by dacleyra** [comment]
The sample was run too quickly after install, the collection containing the pipeline is not resolved by the kabanero operator yet. Sample needs a wait check loop.

**Comment by dacleyra** [comment]
Sample is updated for 0.1.0 release, and now resides in this repository.
https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts

Please give it a try

**Comment by alohr51** [comment]
@jagraj were you able to get past this issue with the updated sample?

**Comment by marikaj123** [comment]
@alohr51 - Is it an issue valid that needs to be addressed for this release.

**Comment by alohr51** [comment]
doesn't seem like we got an update, I would assume Dans update above fixes it.

**Comment by dacleyra** [comment]
AFAIK, this is resolved, as others were able to successfully execute the scenario.

**Comment by jagraj** [comment]
Thanks Dan for closing, Our team is not testing with Kabanero stack. we are going to start testing for our next release for Eclipse Che support.
