### ISSUE TITLE
Write a Guide for "Using the NodeJS Express Collection" 

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#48]
There are 3 opensource NodeJS Collections for MVP:

NodeJS
NodeJS Express
NodeJS LoopBack
These require a Guide, either one guide for all 3 or one guide per collection.

Updated 18th November:

- This issue is for the Nodejs Express collection guide.
- guide must be identical to the MicroProfile and Spring Boot guides already published, replacing the elements unique to this collection.

**Comment by SueChaplain** [comment]
I'm unable to self-assign this item. @bschrammIBM do you know if I need to be added to a team or org?

**Comment by marikaj123** [comment]
@SueChaplain - Is the content ready for Alan/Nate to review? If yes, please make them as reviewers to the PR.  Please ping me in case of any questions you may have. Thank you.

**Comment by SueChaplain** [comment]
This one won't be ready @marikaj123 - there are still some blocking items. 

From an earlier comment:

>This work is stalled for the time being due to the following;

> - code gap in Codewind for setting a default repo
> - possible code gap in Codewind for deploy steps
> - sample microservices app needed for example

I had been given a workaround for setting a default repo, but can't get this to work in practice (back to the drawing board). There is no ability to deploy through VS Code/Codewind, so the guide will go as far as build. I still have no "simple" microservices app example to use for this guide so that it is not overly long or complicated.

As soon as I can close the remaining problems the guide can go for review. Hopefully it will follow shortly after the 0.2 release.

**Comment by SueChaplain** [comment]
Latest progress in PR: https://github.com/kabanero-io/draft-guide-collection-nodejs/pull/2

In my opinion, not ready yet.

**Comment by marikaj123** [comment]
@SueChaplain - Let us know what are the next steps to get the issue closed.

**Comment by SueChaplain** [comment]
@marikaj123 
>Let us know what are the next steps to get the issue closed.

- I have added steps for setting the repository to point to Kabanero, which a codewind developer is checking for me.
- I need a sample Node.js microservices application to use as part of the guide (similar to the ones we have for microprofile and Spring). I'm getting some help with this from Bazif.

Hope to have this guide ready for review by Alan in a couple of days.

**Comment by SueChaplain** [comment]
Ready for review @ralanlittle & @nateziemann in PR: https://github.com/kabanero-io/draft-guide-collection-nodejs/pull/3

**Comment by SueChaplain** [comment]
@ralanlittle & @nateziemann - I merged the PR to make it easier for your to review from master.

**Comment by SueChaplain** [comment]
Andrew has kindly staged these at: https://kabanero-ajlohr.us-south.cf.test.appdomain.cloud/guides/

**Comment by jopit** [comment]
The section https://github.com/kabanero-io/draft-guide-collection-nodejs#configuring-your-environment-to-use-a-kabanero-collection-hub talks about manually editing the `.config/repository_list.json` file.

The better way to do this is by right-clicking on the `Projects` item in the Codewind view and selecting `Manage Tempate sources` from the menu.  This will present a view that allows the Kabanero Collections to be enabled by  clicking a radio button.

You can also open this view by entering `codewind: manage template sources` in the vscode command palette.

The Template Sources Manager UI also allows the user to add their own template sources to their installation of Codewind.

**Comment by SueChaplain** [comment]
Thanks for the feedback @jopit - I'll get those changes made asap.
Is the `Manage Template sources` view new? This guide was started some time ago and I remember Toby mentioning that there were new UI capabilities coming along.

**Comment by jopit** [comment]
The `Manage Template Sources` view was added about a month ago, in the 0.4.0 Codewind release

**Comment by SueChaplain** [comment]
>The Manage Template Sources view was added about a month ago, in the 0.4.0 Codewind release

OK, well .... bad timing or bad info. I'll get it fixed.

**Comment by SueChaplain** [comment]
@jopit - thanks for your review on the PR, now merged.

@ralanlittle and @nateziemann - comments from John are addressed, guide back in the review queue.

**Comment by SueChaplain** [comment]
Following review with Nathan, this guide needs a re-write. It should be identical to the MicroProfile and SpringBoot guides that are currently published.

- remove VS Code / Codewind instructions / images / explanations
- base it on using Appsody CLI

Also, Nathan wants a guide for every collection. So that means 3 guides for each of the Nodejs options: base, Express, and Loopback.

This guide covers Express, so creating 2 further issues for guides on the others.

**Comment by SueChaplain** [comment]
@alohr51 - this guide approved and now ready to publish. 
Website team are admins on the repo. Thank you!

**Comment by alohr51** [comment]
Our setup uses Kramdown, it might be possible https://kramdown.gettalong.org/documentation.html

**Comment by alohr51** [comment]
published at https://kabanero.io/guides/collection-nodejs-express/
