### ISSUE TITLE
Incorporate Logging and Monitoring for OpenShift information in a Guide

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#50]
There are two source documents that need to be incorporated into a Guide.
https://github.com/fwji/openshift-logging - This applies to collections running on OpenLiberty.
https://github.com/fwji/openshift-monitoring applies to all collections running on OpenShift/OKD

The logging info could be part of the OpenLiberty Guide.
The monitoring applies to all collections.

Need to determine whether this warrants a separate "Configuring logging and monitoring" Guide.

**Comment by fwji** [comment]
@ralanlittle Hi Alan, please add me to this repository as a collaborator so I can assign myself to the issue.

**Comment by bschrammIBM** [comment]
@jantley-ibm Frank would like someone to polish his text.

**Comment by jantley-ibm** [comment]
@chirp1 See above, ready for review

**Comment by t-koman** [comment]
@chirp1 @fwji Karen or Frank - how best to edit these two topics and present the results in Git. ?

**Comment by alohr51** [comment]
@t-koman you can go to each README 
  * https://github.com/kabanero-io/guide-logging
  * https://github.com/kabanero-io/guide-monitoring 

and click the pencil icon in the upper right, make your changes and then at the bottom check the bubble "Create a new branch for this commit and start a pull request.", give your branch a name, and hit commit.

This should open a PR you can get someone to look at either me / Karen / Frank.

**Comment by bschrammIBM** [comment]
@t-koman @chirp1 Can one of you review and polish the text here: https://github.com/fwji/openshift-monitoring

**Comment by alohr51** [comment]
@bschrammIBM @t-koman @chirp1 the actual guide link that needs the polish is https://github.com/kabanero-io/guide-app-monitoring

**Comment by fwji** [comment]
We are investigating a claim where the bring-your-own Prometheus Operator picking up Prometheus CRD deployed in openshift-monitoring. This is an unwanted behavior and should be avoided. And I am also studying about a possible workaround of modifying the bundle.yaml to limit the governance of Prometheus Operator to one namespace.

**Comment by fwji** [comment]
The workaround has been found for deploying multiple prometheus operators without conflict. I have updated the guide with the workaround.

**Comment by marikaj123** [comment]
@fwji and @alohr51 - Any reason why this held back from being published?

**Comment by alohr51** [comment]
Yeah it's not approved yet.

**Comment by bschrammIBM** [comment]
Labeled as ready-to-publish @ralanlittle approved these guides via a slack message: 

```
Alan Little 12:47 PM
This one "draft-guide-app-logging" is approved.  There is no way to approved it because we dont seem to be using PRs
Alan Little 12:54 PM
And I approve "draft-guide-app-monitoring"

```

**Comment by mingcyu** [comment]
Live on Kabanero site. Closing this issue
