### ISSUE TITLE
Document how to configure the Tekton Dashboard Webhooks

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#51]
This could go in a "Working with Pipelines Guide" or as part of the Collections guide.
https://github.com/mnuttall/experimental/blob/docs.for.54/webhooks-extension/docs/GettingStarted.md

**Comment by jantley-ibm** [comment]
Needs ID assignment

**Comment by mtamboli** [comment]
Lot of people are asking for this doc. I can provide some help on this document as I am having some success creating a working web hook. I think we need to update the below link as well https://kabanero.io/docs/#tektonUI-webhook.html

**Comment by bschrammIBM** [comment]
@mtamboli Please provide updates to both https://github.com/mnuttall/experimental/blob/docs.for.54/webhooks-extension/docs/GettingStarted.md and https://kabanero.io/docs/#tektonUI-webhook.html. This is a priority.

**Comment by kvijai82** [comment]
@bschrammIBM I updated the kabanero-pipelines repo readme to walk through the different ways to run a pipeline.  Alan wanted to get that in the docs as well.  The tekton-dashboard webhook setup I don't think we should duplicate the info but rather update what they have in https://github.com/mnuttall/experimental/blob/docs.for.54/webhooks-extension/docs/GettingStarted.md as that can very easily go out of date when they make updates.

**Comment by kvijai82** [comment]
https://github.com/kabanero-io/kabanero-pipelines/blob/Readme-updates/README.md is the pipelines doc for now.  If something is not clear please let me know and we can make it better.  @mtamboli please review and provide feedback as well.

**Comment by bschrammIBM** [comment]
@kvijai82 Please clarify what needs to be documented for the Tekton webhooks for customers.
Does a customer need to perform the steps in https://github.com/kabanero-io/kabanero-pipelines/blob/Readme-updates/README.md ? Or do they simply use the Webhooks option on the Tekton dashboard?

**Comment by bschrammIBM** [comment]
@mtamboli @kvijai82 There are several readmes regarding configuring the Tekton webhooks. Please clarify what a customer needs to do for the release on 9/13

**Comment by mtamboli** [comment]
@bschrammIBM Barbara, I think user is expected to use Tekton dashboard to create webhook although there is nothing preventing them to follow other ways. We have documented scenario in our test issues. @ralanlittle will review and pass it over to docs.

**Comment by mingcyu** [comment]
Here is a recording that has a demo of how someone creating a SpringBoot application creates the web hook https://ibm.box.com/s/avi2988zqoyz26bsv4mw12x9tgvctfqe

**Comment by dmuelle** [comment]
Hi @bschrammIBM @mtamboli 

I'll be handling ID team responsibilities for this doc. From what I can gather by reading the comments, I'm currently waiting on the doc mentioned in the previous comment to proceed.

If that's not the case, or if there's anything I ca do in the meantime, just let me know. I can certainly update/ flesh out  https://kabanero.io/docs/#tektonUI-webhook.html with info from https://github.com/mnuttall/experimental/blob/docs.for.54/webhooks-extension/docs/GettingStarted.md  but I don't want to needlessly duplicate anything or provide info that has since changed.

Thanks!

**Comment by dmuelle** [comment]
updated doc is at https://github.com/kabanero-io/docs/blob/master/ref/general/tekton-webhooks.adoc

@bschrammIBM the filename is slightly different but @alohr51 says it will not matter and the site will build the page regardless.

**Comment by alohr51** [comment]
this is published https://kabanero.io/docs/ref/general/tekton-webhooks.html
