### ISSUE TITLE
Write a guide for "Using kAppNav" the application navigator

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#57]
The kAppNav tool is part of the kabanero release.
It is the open source version of Application Navigator https://www.ibm.com/support/knowledgecenter/en/SS7K4U_9.0.5/com.ibm.websphere.zseries.doc/ae/ccld_appnav.html
The engineering contact is: Chris Vignola 
See https://github.com/kappnav/README

**Comment by marikaj123** [comment]
Need kAppVav team to help with this.

**Comment by bschrammIBM** [comment]
Title could be: `How to manage microservice-based apps using kAppNav`

**Comment by marikaj123** [comment]
According to Richard and Chris V, the issue will be completed by this Friday.

**Comment by marikaj123** [comment]
According to Chris, the team is looking to out the appnav guide on kabanero.io

**Comment by bschrammIBM** [comment]
Dolores Lopez has source material for the kAppNav guide, according to slack message:

```Dolores Lopez:2 hours ago
Hello, I am looking for information on how to add kAppNav documentation in Kabanero.io.
1)    Are there any guidelines/procedures we need to follow to format and submit docs
2)    Who needs to review/approve them
3)    What are the datelines to submit doc to be included in Kabanero operator 0.2.0```

+1-512-286-7283 (Office)
doloresl@us.ibm.com
Dolores Lopez/Austin/IBM

**Comment by marikaj123** [comment]
@bschrammIBM - Would we consider this issue as a duplicate of introduce KnappNav in kabanero.io #231? If, yes, can it be closed?

**Comment by alohr51** [comment]
@marikaj123 kabanero-io/kabanero-website/issues/231 is about adding a mention of kAppNav to the website pages itself, this one is writing a **guide** for kAppNav that would also go on the website so I wouldn't consider them duplicates.

**Comment by cvignola** [comment]
@Rwalls1 Draft here:  https://ibm.box.com/s/berqr4swcnm3m56kuzigf32a6k8fu2y4

**Comment by Rwalls1** [comment]
@cvignola @ralanlittle @nateziemann Guide at https://github.com/kabanero-io/draft-guide-using-kAppNav is ready for review.

**Comment by Rwalls1** [comment]
@ralanlittle @nateziemann Please review: https://github.com/kabanero-io/draft-guide-using-kAppNav

**Comment by mingcyu** [comment]
Live on Kabanero site. Closing this issue
