### ISSUE TITLE
Provide an outline for the guides for the Collections

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#58]
A generic outline for what sort of topics need to be covered in the Guides for the Collections is needed to start the writing effort.

We now have Guides that are published on the stage site for kabanero.io. @ralanlittle please review and provide feedback to improve the content.

**Comment by bschrammIBM** [comment]
@ralanlittle Please review the Guides on the stage site for kabanero.io and provide feedback. Is this the best content for the Guides? Anything missing? 

https://kabanero.us-south.cf.test.appdomain.cloud/guides/guide-collection-microprofile/README.html

https://kabanero.us-south.cf.test.appdomain.cloud/guides/guide-collection-springboot2/README.html

**Comment by SueChaplain** [comment]
Assume that the Guides we produced for GA were acceptable since they are now live:

- https://kabanero.io/guides/collection-microprofile/
- https://kabanero.io/guides/collection-springboot2/

@ming - recommend we close this issue. Do you agree?

**Comment by bschrammIBM** [comment]
Yes this issue can be closed. It is no longer relevant as Guide production is moving forward.
