### ISSUE TITLE
Add collection curation experience to the documentation and kabanero-io website

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/docs#59]
The initial collection curation support for "Champ -- Enterprise Architect" has dropped in the 0.1.0 release of the collections.  The team supporting collections are documenting that experience with this issue: https://github.com/kabanero-io/kabanero-collection/issues/51.  This needs to make its way to formal documentation and the kabanero-io champ collection try it experience.

**Comment by groeges** [comment]
What is actually needed for this?

**Comment by mtamboli** [comment]
Would like to see document on how Champ can create/update/delete collections for testing.

**Comment by stephenkinder** [comment]
@groeges We need a simple example of how one can clone and modify the default collections for usage with the kabanero operator.   Collection curation is a key feature we are trying to demonstrate.   I could think of a couple of scenarios:

1) removing an unwanted collection
2) adding an experimental collection
3) changing the fixpack level or OS image understand one of the stacks.

**Comment by mtamboli** [comment]
We have above scenarios mentioned by @stephenkinder planned for testing but do not have information on how to do it. If you have draft instructions, I would be happy to give it a try.

**Comment by bschrammIBM** [comment]
@mtamboli There are instructions available to test here https://github.com/kabanero-io/collections/blob/master/README.md  Please update the instructions based on your tests.

**Comment by davco01a** [comment]
please see:  https://github.com/kabanero-io/docs/issues/66 for setting collection URL into the operator CRD

**Comment by davco01a** [comment]
cloned collection URL needs to be specified by Todd in the repository URL of the kab operator CRD

**Comment by marikaj123** [comment]
@groeges - Can you please help with closing this issue.

**Comment by jantley-ibm** [comment]
This is the Kabanero.io docs version: https://kabanero.io/docs/ref/general/collection-building.html
OK to close?

**Comment by mtamboli** [comment]
@jantley-ibm These instructions are not yet clear to me. I am not sure how step 3 fits into that doc.

**Comment by davco01a** [comment]
Couple of comments/corrections:

```
The URL setting is in the Spec.Collections.Repositories section of the Kabanero instance. 
```
should read
```
The URL setting is in the Spec.Collections.Repositories section of the CRD document for the Kabanero instance. 
```

**Comment by davco01a** [comment]
```
In the Kabanero instance, specify: git organization in the organization field git team name(s) in the teams field the api github url in the apiurl field
```
should read
```
In the CRD document for the Kabanero instance, specify: git organization in the `organization` field git team name(s) in the `teams` field and the api github url in the `apiurl` field
```

**Comment by davco01a** [comment]
@kaczyns Please double check me if my comments make sense in the local environment, thanks

**Comment by kaczyns** [comment]
> Couple of comments/corrections:
> 
> ```
> The URL setting is in the Spec.Collections.Repositories section of the Kabanero instance. 
> ```
> 
> should read
> 
> ```
> The URL setting is in the Spec.Collections.Repositories section of the CRD document for the Kabanero instance. 
> ```

We need to stop calling this "the CRD document".  The CRD is the "Custom Resource Definition", it's the model that describes how to make a CR instance.  In the sentence, `Kabanero instance` refers to the CR instance of the `Kabanero CRD`.  I think that the original working is correct, because Kabanero is a `Kind` in Kubernetes (defined by the Kabanero CRD).

**Comment by davco01a** [comment]
Thanks Tim.

I still think we should take @mtamboli 's comments to heart and see how to make it clearer ( if possible ) before closing it out:

```
@jantley-ibm These instructions are not yet clear to me. I am not sure how step 3 fits into that doc.
```

**Comment by kaczyns** [comment]
OK, I will go look at some other projects and see how they refer to their CR instances.  I think we may not have done ourselves any favors by naming our CR instance `Kabanero` when the name of our project is also called Kabanero.

**Comment by marikaj123** [comment]
Need Monica and Jeff to review the doc.

**Comment by marikaj123** [comment]
@kaczyns - Is any work pending from the collection team, @ianpartridge  for this issue?

**Comment by kaczyns** [comment]
@marikaj123 I don't think @mtamboli is finished going thru the steps yet, so I'm not sure if we need more from the collection team.

**Comment by mtamboli** [comment]
> @marikaj123 I don't think @mtamboli is finished going thru the steps yet, so I'm not sure if we need more from the collection team.

@kaczyns Do you think any of the information requested in this issues is covered in the docs you are updating? I think this should come from collections team? Am I missing a doc which might already be there?

```
removing an unwanted collection
adding an experimental collection
changing the fixpack level or OS image understand one of the stacks.
```

**Comment by kaczyns** [comment]
Hi @mtamboli - I'm not sure what team would be responsible for those things.  It's not the operator team.  The first two sounds like maybe the collections team.  The third one, I'm not sure.  That might fall on the user.

**Comment by marikaj123** [comment]
Do we have the doc created for Champ to add and delete a collection?  How can Champ change a fixpack level of a Java Microprofile?

**Comment by groeges** [comment]
@marikaj123 Sue Chaplain is generating a document on how Champ would add or exclude/delete a collection. 
As to how Champ would change the stack in a collection that is more an Appsody stack question. The collections team are not the experts on each of the stacks. The instructions on how and what can be modified in a stack is probably best coming from the stack owners.

**Comment by marikaj123** [comment]
Based on the meeting we had today SVT (@mtamboli ) has what it needs to run the scenario and @SueChaplain will complete the work by this Friday.

**Comment by marikaj123** [comment]
@SueChaplain - Is it ready to close?

**Comment by SueChaplain** [comment]
@marikaj123 - the main work is tracked in #55. The guide is complete, but like others, it is in review. If @mtamboli is happy (?), you could close this one and we leave #55 open until Alan and Nate complete their review.

**Comment by mtamboli** [comment]
As Sue above recommended, will close this issue.
