### ISSUE TITLE
Define security setup configuration for Management CLI

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/docs#60]
After installing Kabanero, the steps documented below are needed before Champ can use the CLI.  This needs to be incorporated either in the install scripts, as a post-install script, or included in website doc

https://github.com/kabanero-io/kabanero-security/wiki/Setting-up-the-CLI-backend-app

**Comment by mtamboli** [comment]
From the document above it seems like a difficult task to setup CLI. As a user, I would like to know in documentation if there are additional capabilities enabled by using Kabanero CLI instead of console.

**Comment by tseelbach** [comment]
I updated the rough draft wiki today.  Specifically i added
-  a line about the relationship of the Kabanero instance to a Github Org.  
- Notes to say that the way we config has changed and been simplified.  We need to confirm and update the wiki with the new -reduced- steps.   Will work with @davco01a and @kaczyns to clarify

**Comment by tseelbach** [comment]
this feature is not commited for 0.1.2.   removing tag

**Comment by davco01a** [comment]
Closing, this has now been documented and simplified by specifying in Kabanero CRD yaml

**Comment by mtamboli** [comment]
@davco01a Which document explains this?

**Comment by davco01a** [comment]
https://github.com/kabanero-io/docs/issues/66
