### ISSUE TITLE
document uninstall of Kabanero

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/docs#62]
Some work in progress notes:  https://github.com/kabanero-io/docs/wiki/uninstall-Kabanero

**Comment by tseelbach** [comment]
Justin Fleming, can we use your script as an example for uninstall?  It works except for problems with finalizers, which is outside the control of the script.  Probably bugs in some of the operators

**Comment by tseelbach** [comment]
see https://github.com/kabanero-io/kabanero-foundation/issues/40

**Comment by marikaj123** [comment]
Need to contact Jeff about the content.

**Comment by dacleyra** [comment]
Uninstall script is here

https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/README.md#uninstallation-scripts

https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/uninstall-kabanero-foundation.sh

**Comment by marikaj123** [comment]
@jantley-ibm - Does the issue contains what is needed for the ID team to provide the 'ID-reviewed' label?

**Comment by marikaj123** [comment]
@alohr51 - Do we need anything specific from the owner before we can get the issue published?

**Comment by alohr51** [comment]
@marikaj123 We need to confirm the doc is correct https://github.com/kabanero-io/docs/blob/master/ref/general/uninstalling-kabanero-foundation.adoc I'm sure @jantley-ibm had it reviewed or similar, but we can double check

**Comment by jantley-ibm** [comment]
@marikaj123 @kaczyns approved the pull request kabanero-io/docs#114, should be good to go
