### ISSUE TITLE
Ensure installation script is accurately documented 

### ISSUE THREAD

**Issue by bschrammIBM** [kabanero-io/docs#68]
The installation script for Kabanero Foundation provided here: https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts needs better documentation.

The following issues have been described:

1) A key aspect missing in the kabanero foundation instructions is that the registry must be secured via SSL and knative-serving has to be aware (or made aware) of the signing cert for the registry. From @nastacio For whatever it is worth, if using MacOS (and possibly Ubuntu 18) , I wrote a script to automate all the steps I took and it completes successfully every time on minishift:
https://gist.github.com/nastacio/df810a53066c34b9242e603ad5ba3b66

2) See https://github.com/kabanero-io/docs/issues/32

3) There are links to OKD documentation and the request is to provide examples or more specifics for what is needed. The links are: 
See more about Configuring Your Inventory File https://docs.okd.io/3.11/install/configuring_inventory_file.html
See more about the Internal Registry
https://docs.okd.io/3.11/install_config/registry/index.html

**Comment by nastacio** [comment]
@jantley-ibm , we need someone in ID to clarify #1 in the docs and someone in the development team to spell out the instructions on #3.

**Comment by bschrammIBM** [comment]
This requires engineering to update the information on https://kabanero.io/docs/#scripted-kabanero-foundation-setup.html

**Comment by bschrammIBM** [comment]
This issue is related to https://github.com/kabanero-io/docs/issues/32

**Comment by alohr51** [comment]
@stephenkinder who own the installation script? they would be helpful in updating the documentation.

**Comment by stephenkinder** [comment]
@alohr51 The "operator team" owns it, perhaps we should add @dacleyra as an owner?  "Who owns the issue" and who owns making it on the website, and who owns making it to KC is a bit of mystery to me. :)

**Comment by alohr51** [comment]
so someone would only need to update https://github.com/kabanero-io/docs/blob/master/ref/general/installing-kabanero-foundation.adoc and it will automatically make it into the website on next website release/push I assume whomever created that file or someone similar could update it.

**Comment by alohr51** [comment]
also looks like @bschrammIBM's original meaning was to update the README in https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts, but the actual install doc could be updated too

**Comment by jantley-ibm** [comment]
@stephenkinder @alohr The KC work has been done primarily by @helyarp so far.  Both the readme and the install doc were in place on the kabanero site before ID got involved, but we can assist if needed

**Comment by alohr51** [comment]
@dacleyra assigning you to see if you can help with any of the 3 installation issues described in the issue description

I assume it might require changes to 
https://github.com/kabanero-io/kabanero-foundation/blob/master/scripts/install-kabanero-foundation.sh

or the install doc

https://github.com/kabanero-io/docs/blob/master/ref/general/installing-kabanero-foundation.adoc

**Comment by dacleyra** [comment]
1. I disagree that we need to be very specific about the configuration, the appropriate reference is provided. 
https://github.com/kabanero-io/kabanero-foundation/tree/master/scripts#prerequisites
There are several ways this can be configured, and it's up to the administrator.

For example, at install time backed by nfs

```
openshift_hosted_registry_storage_kind=nfs
openshift_hosted_registry_storage_access_modes=['ReadWriteMany']
openshift_hosted_registry_storage_nfs_directory=/exports
openshift_hosted_registry_storage_nfs_options='*(rw,root_squash)'
openshift_hosted_registry_storage_volume_name=registry
openshift_hosted_registry_storage_volume_size=10Gi
openshift_hosted_registry_storage_host=n.n.n.n
```

I'm not familiar with the configuration @nastacio requires

There are probably some logistical differences between this configuration for OKD and minishift. This is documented to support OKD.


2. The linked page in #32 is a 404. Not sure what action is required here.

3. OK. I will provide the above example for #1 in the README.

**Comment by alohr51** [comment]
I closed #32 as it referenced a link not in the [latest install doc](https://github.com/kabanero-io/docs/blob/master/ref/general/installing-kabanero-foundation.adoc) anymore.

**Comment by dacleyra** [comment]
Proposed changes, anything else?

https://github.com/kabanero-io/kabanero-foundation/pull/95

**Comment by dacleyra** [comment]
No feedback, assuming satisfactory, merged and closing
