### ISSUE TITLE
Need to version docs for a release.

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/docs#70]
When we cut a release we need a way to `version` the docs for that release.  What is our strategy and plan to do that?

**Comment by alohr51** [comment]
So here is the plan

We are going to match the Kabanero release process for the docs. This includes the following

`0.2.0` will be used in the below example:

1. When a new release of Kabanero as a whole is ready the next version number will always be a Major or Minor bump (never a patch bump).

1. If **after a release**, A piece of Kabanero (cli,pipelines,operator,docs, etc...) needs to do a small update or a quick bug fix or something (and should be deployed **before the next scheduled release**) 
   1. Create a `release-0.2` branch based off the `0.2.0` release tag
   1.  Put the changes in the `release-0.2` branch (and master)
   1. Cut a new release (based off the branch release-0.2) and bump the patch # so the release becomes `0.2.1`
   1.  publish the `0.2.1` release and deploy

Note: During all the above shenanigans, the `master` branch will still always be the latest changes for the next release.

---
Now for the website

The build already clones the repo, but now needs  to go through each release available using the git cli and put the release names (0.2.0 for example) in a liquid array variable which will be used to populate a dropdown menu on the /docs page.
   * During that churn it should also put all the /ref/docs/general/* docs into a versioned labeled folder in the /docs directory, for example `/docs/0.2.0/ref/general/installing-kabanero-foundation.html`

When a new doc version is selected in that dropdown the page will load the docs from that release.
   1. This can be done by having the build put the versioned docs under the /docs directory under a new folder labeled with the release
   1. Then the dropdown can load the page /docs/0.2.0 which will show all the versioned 0.2.0 docs from the repository
   1. /docs should always go to the latest release
