### ISSUE TITLE
Capture / agree tag names for the guides

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/docs#74]
@Charlotte-Holt and I were discussing which "tags" to use in the collections guides to keep things consistent. We thought it would be a good idea to create an issue so that this can be tracked. Having too many tags might be problematic (assuming they are used as a filter), so capturing them allows others to re-use the tags, where appropriate, rather than creating new ones.

Edit this description to add the tag names you have used, and re-use any that are appropriate:

- collection
- nodejs
- express
- Java
- MicroProfile
- Spring
- Spring Boot
- Tomcat
- Appsody
- CLI

**Comment by alohr51** [comment]
A good place to put approved tags would be in the README under https://github.com/kabanero-io/kabanero-website#contributing-to-the-guides

**Comment by alohr51** [comment]
@kidus60 is working on #98, Kidus can you add the tags to the template too under a bullet section called: "Approved tags for guides" ? once you do that feel free to close this issue too
