### ISSUE TITLE
Need to explain concept of collections appropriately in docs

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/docs#99]
Jane/Developer starts with appsody which has concept of stacks. [CLI example ](https://kabanero.io/developer/cli/) talks about Kabanero collections. At this point, Jane only knows about stacks. We need some explanation on how collections are extension of stacks and so appsody can work with collection repository too. 
This explanation also needed for [champ doc](https://kabanero.io/architect/collection-management/)

FYI, @groeges

**Comment by SueChaplain** [comment]
I thought that this page (https://kabanero.io/developer/cli/) was being replaced by a new Getting Started section. If it is also required for the new page, there is possible reuse from here:   https://kabanero.io/guides/overview/

or

**Kabanero Collections**

A Kabanero Collection defines a logical set of software components for developing applications that can be built and deployed to container platforms.

These components include the application stack for a specific programming language, plus container build and deployment artifacts such as Tekton pipelines.

**Comment by marikaj123** [comment]
@SueChaplain -  Can you provide clarity on whether the Kabanero guides will include content regarding the difference between stacks and collection?

**Comment by SueChaplain** [comment]
@marikaj123 - I would expect this guide to cover that: https://github.com/kabanero-io/docs/issues/55.

I've raised PR https://github.com/kabanero-io/kabanero-website/pull/250 to add a small update to the page for this issue, which I hope @mtamboli is ok with ahead of the new Getting Started section that is being worked on here: https://github.com/kabanero-io/kabanero-website/issues/188 (currently being reviewed by Nate & Alan I believe)
